# Generated by Django 5.1.7 on 2025-03-20 13:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanbakh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='شماره تنخواه')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING', 'در حال بررسی'), ('APPROVED', 'تأییدشده'), ('SENT_TO_HQ', 'ارسال\u200cشده به HQ'), ('HQ_OPS_PENDING', 'در حال بررسی - بهره\u200cبرداری'), ('HQ_OPS_APPROVED', 'تأییدشده - بهره\u200cبرداری'), ('HQ_FIN_PENDING', 'در حال بررسی - مالی'), ('PAID', 'پرداخت\u200cشده'), ('REJECTED', 'ردشده')], default='DRAFT', max_length=20, verbose_name='وضعیت')),
                ('hq_status', models.CharField(blank=True, choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING', 'در حال بررسی'), ('APPROVED', 'تأییدشده'), ('SENT_TO_HQ', 'ارسال\u200cشده به HQ'), ('HQ_OPS_PENDING', 'در حال بررسی - بهره\u200cبرداری'), ('HQ_OPS_APPROVED', 'تأییدشده - بهره\u200cبرداری'), ('HQ_FIN_PENDING', 'در حال بررسی - مالی'), ('PAID', 'پرداخت\u200cشده'), ('REJECTED', 'ردشده')], max_length=20, null=True, verbose_name='وضعیت در HQ')),
                ('letter_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره نامه')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanbakh_approved', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanbakh_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('last_stopped_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post', verbose_name='آخرین پست متوقف\u200cشده')),
                ('organization', models.ForeignKey(limit_choices_to={'org_type': 'COMPLEX'}, on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='مجتمع')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تنخواه',
                'verbose_name_plural': 'تنخواه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='شماره فاکتور')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='factors/%Y/%m/%d/', verbose_name='فایل پیوست')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('status', models.CharField(choices=[('PENDING', 'در حال بررسی'), ('APPROVED', 'تأییدشده'), ('REJECTED', 'ردشده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('tanbakh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='tanbakh.tanbakh', verbose_name='تنخواه')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('branch', models.CharField(choices=[('OPS', 'بهره\u200cبرداری'), ('FIN', 'مالی و اداری'), ('COMPLEX', 'مجتمع')], max_length=10, verbose_name='شاخه')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده؟')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tanbakh.factor', verbose_name='فاکتور')),
                ('tanbakh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tanbakh.tanbakh', verbose_name='تنخواه')),
            ],
            options={
                'verbose_name': 'تأیید',
                'verbose_name_plural': 'تأییدات',
            },
        ),
    ]
