# Generated by Django 5.1.7 on 2025-03-22 07:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_workflowstage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_Tankhah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('Dashboard_Tankhah_view', 'دسترسی به داشبورد تنخواه گردان ')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='شماره فاکتور')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('PENDING', 'در حال بررسی'), ('APPROVED', 'تأییدشده'), ('REJECTED', 'ردشده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'permissions': [('Factor_add', 'افزودن فاکتور برای جزئیات تنخواه '), ('Factor_update', 'ویرایش فاکتور برای جزئیات تنخواه'), ('Factor_delete', 'حــذف فاکتور برای جزئیات تنخواه'), ('Factor_view', 'نمایش فاکتور برای جزئیات تنخواه')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FactorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='factors/documents/%Y/%m/%d/', verbose_name='فایل پیوست')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tanbakh.factor', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'سند فاکتور',
                'verbose_name_plural': 'اسناد فاکتور',
            },
        ),
        migrations.CreateModel(
            name='FactorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='شرح ردیف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('status', models.CharField(choices=[('PENDING', 'در حال بررسی'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tanbakh.factor', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'ردیف فاکتور',
                'verbose_name_plural': 'ردیف\u200cهای فاکتور',
                'permissions': [('FactorItem_add', 'افزودن اقلام فاکتور'), ('FactorItem_update', 'ویرایش اقلام فاکتور'), ('FactorItem_view', 'نمایش اقلام فاکتور'), ('FactorItem_delete', 'حذف اقلام فاکتور')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StageApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='پست مجاز')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workflowstage', verbose_name='مرحله')),
            ],
            options={
                'verbose_name': 'تأییدکننده مرحله',
                'verbose_name_plural': 'تأییدکنندگان مرحله',
                'permissions': [('stageapprover__view', 'نمایش تأییدکننده مرحله'), ('stageapprover__add', 'افزودن تأییدکننده مرحله'), ('stageapprover__Update', 'بروزرسانی تأییدکننده مرحله'), ('stageapprover__delete', 'حــذف تأییدکننده مرحله')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Tanbakh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='شماره تنخواه')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING', 'در حال بررسی'), ('APPROVED', 'تأییدشده'), ('SENT_TO_HQ', 'ارسال\u200cشده به HQ'), ('HQ_OPS_PENDING', 'در حال بررسی - بهره\u200cبرداری'), ('HQ_OPS_APPROVED', 'تأییدشده - بهره\u200cبرداری'), ('HQ_FIN_PENDING', 'در حال بررسی - مالی'), ('PAID', 'پرداخت\u200cشده'), ('REJECTED', 'ردشده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد  ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('due_date', models.DateField(verbose_name='مهلت زمانی')),
                ('hq_status', models.CharField(blank=True, choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING', 'در حال بررسی'), ('APPROVED', 'تأییدشده'), ('SENT_TO_HQ', 'ارسال\u200cشده به HQ'), ('HQ_OPS_PENDING', 'در حال بررسی - بهره\u200cبرداری'), ('HQ_OPS_APPROVED', 'تأییدشده - بهره\u200cبرداری'), ('HQ_FIN_PENDING', 'در حال بررسی - مالی'), ('PAID', 'پرداخت\u200cشده'), ('REJECTED', 'ردشده')], max_length=20, null=True, verbose_name='وضعیت در HQ')),
                ('letter_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره نامه')),
                ('description', models.TextField()),
                ('approved_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='تأییدکنندگان')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanbakh_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workflowstage', verbose_name='مرحله فعلی')),
                ('last_stopped_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post', verbose_name='آخرین پست متوقف\u200cشده')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='سازمان')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تنخواه',
                'verbose_name_plural': 'تنخواه\u200cها',
                'permissions': [('Tanbakh_add', 'ثبت تنخواه'), ('Tanbakh_update', 'بروزرسانی تنخواه'), ('Tanbakh_view', 'نمایش تنخواه'), ('Tanbakh_delete', 'حذف تنخواه'), ('Tanbakh_part_approve', 'تأیید رئیس قسمت'), ('Tanbakh_approve', 'تأیید مدیر مجموعه'), ('Tanbakh_hq_view', 'رصد دفتر مرکزی'), ('Tanbakh_hq_approve', 'تأیید رده بالا در دفتر مرکزی'), ('Tanbakh_HQ_OPS_PENDING', 'در حال بررسی - بهره\u200cبرداری'), ('Tanbakh_HQ_OPS_APPROVED', 'تأییدشده - بهره\u200cبرداری'), ('Tanbakh_HQ_FIN_PENDING', 'در حال بررسی - مالی'), ('Tanbakh_PAID', 'پرداخت\u200cشده'), ('Tanbakh_REJECTED', 'ردشده')],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='factor',
            name='tanbakh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='tanbakh.tanbakh', verbose_name='تنخواه'),
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVE', 'تأیید'), ('REJECT', 'رد'), ('EDIT', 'ویرایش')], max_length=10, verbose_name='اقدام')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post', verbose_name='پست تأییدکننده')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workflowstage', verbose_name='مرحله')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='tanbakh.factor', verbose_name='فاکتور')),
                ('factor_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='tanbakh.factoritem', verbose_name='ردیف فاکتور')),
                ('tanbakh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='tanbakh.tanbakh', verbose_name='تنخواه')),
            ],
            options={
                'verbose_name': 'تأیید',
                'verbose_name_plural': 'تأییدات👍',
                'permissions': [('Approval_add', 'افزودن تأیید برای ثبت اقدامات تأیید یا رد '), ('Approval_update', 'ویرایش تأیید برای ثبت اقدامات تأیید یا رد'), ('Approval_delete', 'حــذف تأیید برای ثبت اقدامات تأیید یا رد'), ('Approval_view', 'نمایش تأیید برای ثبت اقدامات تأیید یا رد')],
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='tanbakh',
            index=models.Index(fields=['number', 'date', 'status'], name='tanbakh_tan_number_22c79a_idx'),
        ),
        migrations.AddIndex(
            model_name='factor',
            index=models.Index(fields=['number', 'date', 'status'], name='tanbakh_fac_number_023a2d_idx'),
        ),
    ]
