# Generated by Django 5.1.7 on 2025-03-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanbakh',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
