# Generated by Django 5.1.7 on 2025-03-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanbakh',
            name='namemamma',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
