# Generated by Django 5.1.7 on 2025-03-20 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_posthistory'),
        ('tanbakh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='factor',
            index=models.Index(fields=['number', 'date', 'status'], name='tanbakh_fac_number_023a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='tanbakh',
            index=models.Index(fields=['number', 'date', 'status'], name='tanbakh_tan_number_22c79a_idx'),
        ),
    ]
