# Generated by Django 5.1.7 on 2025-03-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0002_tanbakh_namemamma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanbakh',
            name='namemamma',
        ),
    ]
