# Generated by Django 5.1.7 on 2025-03-22 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0002_alter_tanbakh_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanbakh',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='tanbakh',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='tanbakh',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت زمانی'),
        ),
    ]
