# Generated by Django 5.1.7 on 2025-03-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0002_factor_tanbakh_fac_number_023a2d_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'default_permissions': (), 'permissions': [('Approval_add', 'افزودن تأیید برای ثبت اقدامات تأیید یا رد '), ('Approval_update', 'ویرایش تأیید برای ثبت اقدامات تأیید یا رد'), ('Approval_delete', 'حــذف تأیید برای ثبت اقدامات تأیید یا رد'), ('Approval_view', 'نمایش تأیید برای ثبت اقدامات تأیید یا رد')], 'verbose_name': 'تأیید', 'verbose_name_plural': 'تأییدات'},
        ),
        migrations.AlterModelOptions(
            name='factor',
            options={'default_permissions': (), 'permissions': [('Factor_add', 'افزودن فاکتور برای جزئیات تنخواه '), ('Factor_update', 'ویرایش فاکتور برای جزئیات تنخواه'), ('Factor_delete', 'حــذف فاکتور برای جزئیات تنخواه'), ('Factor_view', 'نمایش فاکتور برای جزئیات تنخواه')], 'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتورها'},
        ),
        migrations.AlterModelOptions(
            name='tanbakh',
            options={'default_permissions': (), 'permissions': [('Tanbakh_add', 'افزودن مدل تنخواه برای ثبت و مدیریت درخواست\u200cهای مالی '), ('Tanbakh_update', 'ویرایش مدل تنخواه برای ثبت و مدیریت درخواست\u200cهای مالی'), ('Tanbakh_delete', 'حــذف مدل تنخواه برای ثبت و مدیریت درخواست\u200cهای مالی'), ('Tanbakh_view', 'نمایش مدل تنخواه برای ثبت و مدیریت درخواست\u200cهای مالی')], 'verbose_name': 'تنخواه', 'verbose_name_plural': 'تنخواه\u200cها'},
        ),
    ]
