# Generated by Django 5.1.7 on 2025-03-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0003_alter_approval_options_alter_factor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanbakh',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanbakh',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tanbakh',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING', 'در حال بررسی'), ('APPROVED', 'تأییدشده'), ('SENT_TO_HQ', 'ارسال\u200cشده به HQ'), ('HQ_OPS_PENDING', 'در حال بررسی - بهره\u200cبرداری'), ('HQ_OPS_APPROVED', 'تأییدشده - بهره\u200cبرداری'), ('HQ_FIN_PENDING', 'در حال بررسی - مالی'), ('PAID', 'پرداخت\u200cشده'), ('REJECTED', 'ردشده')], default='PENDING', max_length=20, verbose_name='وضعیت'),
        ),
    ]
