# Generated by Django 5.1.7 on 2025-03-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0003_alter_tanbakh_created_at_alter_tanbakh_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tanbakh',
            options={'default_permissions': (), 'permissions': [('Tanbakh_add', 'ثبت تنخواه'), ('Tanbakh_update', 'بروزرسانی تنخواه'), ('Tanbakh_view', 'نمایش تنخواه'), ('Tanbakh_delete', 'حذف تنخواه'), ('Tanbakh_part_approve', 'تأیید رئیس قسمت'), ('Tanbakh_approve', 'تأیید مدیر مجموعه'), ('Tanbakh_hq_view', 'رصد دفتر مرکزی'), ('Tanbakh_hq_approve', 'تأیید رده بالا در دفتر مرکزی'), ('Tanbakh_HQ_OPS_PENDING', 'در حال بررسی - بهره\u200cبرداری'), ('Tanbakh_HQ_OPS_APPROVED', 'تأییدشده - بهره\u200cبرداری'), ('Tanbakh_HQ_FIN_PENDING', 'در حال بررسی - مالی'), ('Tanbakh_PAID', 'پرداخت\u200cشده'), ('Tanbakh_REJECTED', 'ردشده'), ('FactorItem_approve', 'تایید/رد ردیف فاکتور')], 'verbose_name': 'تنخواه', 'verbose_name_plural': 'تنخواه\u200cها'},
        ),
    ]
