# Generated by Django 5.1.7 on 2025-03-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0004_alter_tanbakh_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='نهایی شده'),
        ),
        migrations.AddField(
            model_name='tanbakh',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='آرشیو شده'),
        ),
    ]
