# Generated by Django 5.1.7 on 2025-03-20 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0004_tanbakh_amount_tanbakh_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='شرح ردیف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tanbakh.factor', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'ردیف فاکتور',
                'verbose_name_plural': 'ردیف\u200cهای فاکتور',
                'permissions': [('FactorItem_add', 'افزودن اقلام فاکتور'), ('FactorItem_update', 'ویرایش اقلام فاکتور'), ('FactorItem_view', 'نمایش اقلام فاکتور'), ('FactorItem_delete', 'حذف اقلام فاکتور')],
                'default_permissions': (),
            },
        ),
    ]
