# Generated by Django 5.1.7 on 2025-03-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0005_factor_is_finalized_tanbakh_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('IndexView_dashboard_view', 'دسترسی به داشبورد تنخواه گردان IndexView_dashboard')],
                'default_permissions': (),
            },
        ),
    ]
