# Generated by Django 5.1.7 on 2025-03-20 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0005_factoritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='factor_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tanbakh.factoritem', verbose_name='ردیف فاکتور'),
        ),
        migrations.AddField(
            model_name='tanbakh',
            name='current_stage',
            field=models.CharField(choices=[('COMPLEX', 'مجتمع'), ('OPS', 'بهره\u200cبرداری'), ('FIN', 'مالی')], default='COMPLEX', max_length=20),
        ),
    ]
