# Generated by Django 5.1.7 on 2025-03-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0006_indexview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexView',
        ),
    ]
