# Generated by Django 5.1.7 on 2025-03-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0006_approval_factor_item_tanbakh_current_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoritem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در حال بررسی'), ('APPROVED', 'تأییدشده'), ('REJECTED', 'ردشده')], default='PENDING', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='tanbakh',
            name='current_stage',
            field=models.CharField(choices=[('COMPLEX', 'مجموعه ها'), ('OPS', 'بهره\u200cبرداری'), ('FIN', 'مالی')], default='COMPLEX', max_length=20),
        ),
    ]
