# Generated by Django 5.1.7 on 2025-03-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0007_delete_indexview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tanbakh',
            options={'default_permissions': (), 'permissions': [('Tanbakh_add', 'ثبت تنخواه'), ('Tanbakh_update', 'بروزرسانی تنخواه'), ('Tanbakh_view', 'نمایش تنخواه'), ('Tanbakh_delete', 'حذف تنخواه'), ('Tanbakh_part_approve', 'تأیید رئیس قسمت'), ('Tanbakh_approve', 'تأیید مدیر مجموعه'), ('Tanbakh_hq_view', 'رصد دفتر مرکزی'), ('Tanbakh_hq_approve', 'تأیید رده بالا در دفتر مرکزی'), ('Tanbakh_HQ_OPS_PENDING', 'در حال بررسی - بهره\u200cبرداری'), ('Tanbakh_HQ_OPS_APPROVED', 'تأییدشده - بهره\u200cبرداری'), ('Tanbakh_HQ_FIN_PENDING', 'در حال بررسی - مالی'), ('Tanbakh_PAID', 'پرداخت\u200cشده'), ('Tanbakh_REJECTED', 'ردشده'), ('FactorItem_approve', 'تایید/رد ردیف فاکتور'), ('edit_full_tanbakh', 'تغییرات کاربری در فاکتور /تایید یا رد ردیف ها ')], 'verbose_name': 'تنخواه', 'verbose_name_plural': 'تنخواه\u200cها'},
        ),
        migrations.AddField(
            model_name='approvallog',
            name='changed_field',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='فیلد تغییر یافته'),
        ),
        migrations.AddField(
            model_name='factor',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='قفل شده'),
        ),
        migrations.AddField(
            model_name='tanbakh',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان آرشیو'),
        ),
        migrations.AddField(
            model_name='tanbakh',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='لغو شده'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='action',
            field=models.CharField(choices=[('APPROVE', 'تأیید'), ('REJECT', 'رد'), ('RETURN', 'بازگشت'), ('CANCEL', 'لغو')], max_length=10, verbose_name='اقدام'),
        ),
    ]
