# Generated by Django 5.1.7 on 2025-03-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0008_alter_tanbakh_options_approvallog_changed_field_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factordocument',
            options={'default_permissions': (), 'permissions': [('FactorDocument_add', 'افزودن سند فاکتور'), ('FactorDocument_update', 'بروزرسانی سند فاکتور'), ('FactorDocument_view', 'نمایش سند فاکتور'), ('FactorDocument_delete', 'حــذف سند فاکتور')], 'verbose_name': 'سند فاکتور', 'verbose_name_plural': 'اسناد فاکتور'},
        ),
    ]
