# Generated by Django 5.1.7 on 2025-03-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0010_alter_tanbakh_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TanbakhFinalApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('TanbakhFinalApproval_view', 'دسترسی تایید یا رد تنخواه گردان ')],
                'default_permissions': (),
            },
        ),
    ]
