# Generated by Django 5.1.7 on 2025-03-23 10:08

import django.db.models.deletion
import tanbakh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dashboardview_flows'),
        ('tanbakh', '0011_tanbakhfinalapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanbakh',
            name='current_stage',
            field=models.ForeignKey(default=tanbakh.models.get_default_workflow_stage, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workflowstage', verbose_name='مرحله فعلی'),
        ),
        migrations.AlterField(
            model_name='tanbakh',
            name='hq_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING', 'در حال بررسی'), ('APPROVED', 'تأییدشده'), ('SENT_TO_HQ', 'ارسال\u200cشده به HQ'), ('HQ_OPS_PENDING', 'در حال بررسی - بهره\u200cبرداری'), ('HQ_OPS_APPROVED', 'تأییدشده - بهره\u200cبرداری'), ('HQ_FIN_PENDING', 'در حال بررسی - مالی'), ('PAID', 'پرداخت\u200cشده'), ('REJECTED', 'ردشده')], default='PENDING', max_length=20, null=True, verbose_name='وضعیت در HQ'),
        ),
        migrations.AlterField(
            model_name='tanbakh',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='مجموعه/شعبه'),
        ),
        migrations.AlterField(
            model_name='tanbakh',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING', 'در حال بررسی'), ('APPROVED', 'تأییدشده'), ('SENT_TO_HQ', 'ارسال\u200cشده به HQ'), ('HQ_OPS_PENDING', 'در حال بررسی - بهره\u200cبرداری'), ('HQ_OPS_APPROVED', 'تأییدشده - بهره\u200cبرداری'), ('HQ_FIN_PENDING', 'در حال بررسی - مالی'), ('PAID', 'پرداخت\u200cشده'), ('REJECTED', 'ردشده')], default='DRAFT', max_length=20, verbose_name='وضعیت'),
        ),
    ]
