# Generated by Django 5.1.7 on 2025-03-24 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dashboardview_flows'),
        ('tanbakh', '0012_alter_tanbakh_current_stage_alter_tanbakh_hq_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factor',
            options={'default_permissions': (), 'permissions': [('a_factor_add', 'افزودن فاکتور برای جزئیات تنخواه '), ('a_factor_update', 'ویرایش فاکتور برای جزئیات تنخواه'), ('a_factor_delete', 'حــذف فاکتور برای جزئیات تنخواه'), ('a_factor_view', 'نمایش فاکتور برای جزئیات تنخواه')], 'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتورها'},
        ),
        migrations.AlterField(
            model_name='tanbakh',
            name='current_stage',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workflowstage', verbose_name='مرحله فعلی'),
        ),
    ]
