# Generated by Django 5.1.7 on 2025-03-24 17:43

import django.db.models.deletion
import tanbakh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0014_alter_tanbakh_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TanbakhDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=tanbakh.models.tanbakh_document_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tanbakh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tanbakh.tanbakh')),
            ],
        ),
    ]
