# Generated by Django 5.1.7 on 2025-03-24 18:00

import tanbakh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanbakh', '0015_tanbakhdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanbakhdocument',
            name='document',
            field=models.FileField(upload_to=tanbakh.models.tanbakh_document_path, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='tanbakhdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود'),
        ),
    ]
