# Generated by Django 5.1.7 on 2025-09-28 05:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد شاخه')),
                ('name', models.CharField(max_length=250, verbose_name='نام شاخه')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'شاخه سازمانی',
                'verbose_name_plural': 'شاخه\u200cهای سازمانی',
                'permissions': [('Branch_add', 'افزودن شاخه سازمانی'), ('Branch_edit', 'ویرایش شاخه سازمانی'), ('Branch_view', 'نمایش شاخه سازمانی'), ('Branch_delete', 'حــذف شاخه سازمانی')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Dashboard_Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('Dashboard_Core_view', 'دسترسی به داشبورد Core پایه')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DashboardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('Dashboard__view', 'دسترسی به داشبورد اصلی 💻')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DashboardView_flows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('DashboardView_flows_view', 'دسترسی به روند تنخواه گردانی ')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DynamicConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('value', models.TextField(verbose_name='مقدار')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('category', models.CharField(max_length=50, verbose_name='دسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'پیکربندی پویا',
                'verbose_name_plural': 'پیکربندی\u200cهای پویا',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationChartAPIView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('OrganizationChartAPIView_view', 'دسترسی به داشبورد چارت سازمانی 💻')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OrganizationChartView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('OrganizationChartView_view', '   دسترسی به گرافیک داشبورد چارت سازمانی 💻')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='نام شعبه/مجتمع/اداره')),
                ('org_type', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='نام شعبه/مجتمع/اداره')),
                ('is_budget_allocatable', models.BooleanField(default=False, verbose_name='قابل استفاده برای تخصیص بودجه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'عنوان مرکز/شعبه/اداره/سازمان',
                'verbose_name_plural': 'عنوان مرکز/شعبه/اداره/سازمان',
                'permissions': [('OrganizationType_add', 'افزودن شعبه/اداره/مجتمع/سازمان'), ('OrganizationType_view', 'نمایش شعبه/اداره/مجتمع/سازمان'), ('OrganizationType_update', 'ویرایش شعبه/اداره/مجتمع/سازمان'), ('OrganizationType_delete', 'حــذف شعبه/اداره/مجتمع/سازمان')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_locked_percentage_default', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد قفل\u200cشده پیش\u200cفرض بودجه')),
                ('budget_warning_threshold_default', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='آستانه هشدار پیش\u200cفرض بودجه')),
                ('budget_warning_action_default', models.CharField(choices=[('NOTIFY', 'اعلان'), ('LOCK', 'قفل'), ('RESTRICT', 'محدود')], default='NOTIFY', max_length=50, verbose_name='اقدام هشدار پیش\u200cفرض بودجه')),
                ('allocation_locked_percentage_default', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد قفل\u200cشده پیش\u200cفرض تخصیص')),
                ('tankhah_used_statuses', models.JSONField(blank=True, default=list, verbose_name='وضعیت\u200cهای مصرف\u200cشده تنخواه')),
                ('tankhah_accessible_organizations', models.JSONField(blank=True, default=list, help_text='لیست ID سازمان\u200cهایی که همه کاربران می\u200cتوانند برای آن\u200cها تنخواه ثبت کنند (مثل دفتر مرکزی)', verbose_name='سازمان\u200cهای مجاز برای ثبت تنخواه')),
                ('tankhah_payment_ceiling_default', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='سقف پرداخت پیش\u200cفرض تنخواه')),
                ('tankhah_payment_ceiling_enabled_default', models.BooleanField(default=False, verbose_name='فعال بودن پیش\u200cفرض سقف پرداخت تنخواه')),
                ('enforce_strict_approval_order', models.BooleanField(default=True, help_text='اگر فعال باشد، کاربر سطح بالاتر نمی\u200cتواند قبل از کاربر سطح پایین اقدام کند.', verbose_name='اجبار ترتیب سلسله\u200cمراتبی تأیید (سطح پایین قبل از سطح بالا)')),
                ('allow_bypass_org_chart', models.BooleanField(default=False, help_text='اگر فعال باشد، قوانین وابسته به پست/سطح می\u200cتوانند نادیده گرفته شوند.', verbose_name='اجازه دور زدن چارت سازمانی برای تأیید')),
                ('allow_action_without_org_chart', models.BooleanField(default=False, help_text='اگر فعال باشد، حتی بدون داشتن پست سازمانی هم اقدام ممکن است.', verbose_name='اجازه اقدام بدون رعایت پست\u200cها')),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
                'permissions': [('SystemSettings_access', 'دسترسی به تنظیمات کلی سیستم')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام اقدام')),
                ('code', models.CharField(help_text='کد منحصر به فرد انگلیسی، مانند SUBMIT', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('display_name', models.CharField(blank=True, help_text='نامی که در UI نمایش داده می\u200cشود', max_length=100, verbose_name='نام نمایشی')),
                ('button_style', models.CharField(blank=True, help_text='primary, success, danger, warning, info, secondary', max_length=50, verbose_name='استایل دکمه')),
                ('icon', models.CharField(blank=True, help_text='نام آیکون FontAwesome بدون fa-', max_length=50, verbose_name='آیکون')),
                ('confirmation_message', models.CharField(blank=True, help_text='پیام تأیید قبل از اجرای اقدام', max_length=255, verbose_name='پیام تأیید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'اقدام گردش کار',
                'verbose_name_plural': '۲. اقدامات گردش کار',
                'permissions': [('Action_add', 'افزودن اقدام گردش کار '), ('Action_update', 'ویرایش اقدام گردش کار '), ('Action_view', 'نمایش اقدام گردش کار '), ('Action_delete', 'حــذف اقدام گردش کار ')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام موجودیت')),
                ('code', models.CharField(help_text='کد منحصر به فرد انگلیسی، مانند FACTORITEM', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('content_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع محتوای مرتبط')),
            ],
            options={
                'verbose_name': 'نوع موجودیت گردش کار',
                'verbose_name_plural': '۰. انواع موجودیت\u200cهای گردش کار',
                'permissions': [('EntityType_add', 'افزودن نوع موجودیت گردش کار '), ('EntityType_update', 'ویرایش نوع موجودیت گردش کار '), ('EntityType_view', 'نمایش نوع موجودیت گردش کار '), ('EntityType_delete', 'حــذف نوع موجودیت گردش کار ')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد سازمان')),
                ('name', models.CharField(max_length=100, verbose_name='نام سازمان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_core', models.BooleanField(default=False, verbose_name='دفتر مرکزی سازمان')),
                ('is_holding', models.BooleanField(default=False, verbose_name=' هلدینگ ')),
                ('is_independent', models.BooleanField(default=False, verbose_name='مستقل')),
                ('parent_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_organizations', to='core.organization', verbose_name='سازمان والد')),
                ('org_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='core.organizationtype', verbose_name='نوع سازمان')),
            ],
            options={
                'verbose_name': 'سازمان',
                'verbose_name_plural': 'سازمان\u200cها',
                'permissions': [('Organization_add', 'افزودن سازمان برای تعریف مجتمع\u200cها و دفتر مرکزی'), ('Organization_update', 'بروزرسانی سازمان برای تعریف مجتمع\u200cها و دفتر مرکزی'), ('Organization_delete', 'حــذف سازمان برای تعریف مجتمع\u200cها و دفتر مرکزی'), ('Organization_view', 'نمایش سازمان برای تعریف مجتمع\u200cها و دفتر مرکزی')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پست')),
                ('level', models.IntegerField(default=1, verbose_name='سطح')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('max_change_level', models.IntegerField(default=1, help_text='حداکثر مرحله\u200cای که این پست می\u200cتواند تغییر دهد', verbose_name='حداکثر سطح تغییر(ارجاع به مرحله قبل تر)')),
                ('is_payment_order_signer', models.BooleanField(default=False, verbose_name='مجاز به امضای دستور پرداخت')),
                ('can_final_approve_factor', models.BooleanField(default=False, verbose_name='مجاز به تأیید نهایی فاکتور')),
                ('can_final_approve_tankhah', models.BooleanField(default=False, verbose_name='مجاز به تأیید نهایی تنخواه')),
                ('can_final_approve_budget', models.BooleanField(default=False, verbose_name='مجاز به تأیید نهایی بودجه')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='شاخه')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='سازمان')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post', verbose_name='پست والد')),
            ],
            options={
                'verbose_name': 'پست سازمانی',
                'verbose_name_plural': 'پست\u200cهای سازمانی',
                'permissions': [('Post_add', 'افزودن  پست سازمانی برای تعریف سلسله مراتب'), ('Post_update', 'بروزرسانی پست سازمانی برای تعریف سلسله مراتب'), ('Post_view', 'نمایش  پست سازمانی برای تعریف سلسله مراتب'), ('Post_delete', 'حــذف  پست سازمانی برای تعریف سلسله مراتب')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_field', models.CharField(help_text='نام فیلدی که تغییر کرده (مثل name یا parent)', max_length=50, verbose_name='فیلد تغییر یافته')),
                ('old_value', models.TextField(blank=True, help_text='مقدار قبلی فیلد قبل از تغییر', null=True, verbose_name='مقدار قبلی')),
                ('new_value', models.TextField(blank=True, help_text='مقدار جدید فیلد بعد از تغییر', null=True, verbose_name='مقدار جدید')),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='زمان ثبت تغییر به صورت خودکار', verbose_name='تاریخ و زمان تغییر')),
                ('changed_by', models.ForeignKey(help_text='کاربری که این تغییر را اعمال کرده', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده')),
                ('post', models.ForeignKey(help_text='پستی که تغییر کرده است', on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='پست سازمانی')),
            ],
            options={
                'verbose_name': 'تاریخچه پست',
                'verbose_name_plural': 'تاریخچه پست\u200cها',
                'ordering': ['-changed_at'],
                'permissions': [('posthistory_view', 'می\u200cتواند تاریخچه پست\u200cها را مشاهده کند'), ('posthistory_add', 'می\u200cتواند تاریخچه پست\u200cها را اضافه کند'), ('posthistory_update', 'می\u200cتواند تاریخچه پست\u200cها را ویرایش کند'), ('posthistory_delete', 'می\u200cتواند تاریخچه پست\u200cها را حذف کند')],
            },
        ),
        migrations.CreateModel(
            name='PostRuleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('TANKHAH', 'تنخواه'), ('FACTOR', 'فاکتور'), ('PAYMENTORDER', 'دستور پرداخت')], default='TANKHAH', max_length=50, verbose_name='نوع موجودیت')),
                ('custom_settings', models.JSONField(blank=True, null=True, verbose_name='تنظیمات سفارشی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.action', verbose_name='اقدام')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='سازمان')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'تخصیص قانون به پست',
                'verbose_name_plural': 'تخصیص\u200cهای قانون به پست\u200cها',
                'permissions': [('PostRuleAssignment_add', 'افزودن تخصیص قانون به پست'), ('PostRuleAssignment_view', 'نمایش تخصیص قانون به پست'), ('PostRuleAssignment_update', 'ویرایش تخصیص قانون به پست'), ('PostRuleAssignment_delete', 'حذف تخصیص قانون به پست')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پروژه')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='کد پروژه')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('priority', models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('HIGH', 'زیاد')], default='MEDIUM', max_length=20, verbose_name='اولویت')),
                ('organizations', models.ManyToManyField(limit_choices_to={'org_type__is_budget_allocatable': True}, to='core.organization', verbose_name='سازمان\u200cهای مرتبط')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه',
                'permissions': [('Project_add', 'افزودن  مجموعه پروژه'), ('Project_update', 'ویرایش مجموعه پروژه'), ('Project_view', 'نمایش مجموعه پروژه'), ('Project_delete', 'حــذف مجموعه پروژه')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام وضعیت')),
                ('code', models.CharField(help_text='کد منحصر به فرد انگلیسی، مانند DRAFT', max_length=50, unique=True)),
                ('is_initial', models.BooleanField(default=False, verbose_name='آیا این وضعیت اولیه (شروع) است؟')),
                ('is_final_approve', models.BooleanField(default=False, verbose_name='وضعیت تأیید نهایی؟')),
                ('is_final_reject', models.BooleanField(default=False, verbose_name='وضعیت رد نهایی؟')),
                ('is_pending', models.BooleanField(default=False, verbose_name='وضعیت در انتظار؟')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت شده؟')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='وضعیت رد شده؟')),
                ('entity_type', models.CharField(blank=True, help_text='نوع موجودیت که این وضعیت برای آن استفاده می\u200cشود، مانند FACTOR, PAYMENTORDER', max_length=50, verbose_name='نوع موجودیت')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'وضعیت گردش کار',
                'verbose_name_plural': '۱. وضعیت\u200cهای گردش کار',
                'permissions': [('Status_add', 'افزودن وضعیت'), ('Status_update ', 'ویرایش وضعیت'), ('Status_view ', 'نمایش وضعیت'), ('Status_delete ', 'حــذف وضعیت')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PostAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('APPROVE', 'تأیید'), ('REJECT', 'رد'), ('SUBMIT', 'ارسال برای تایید'), ('FINAL_APPROVE', 'تایید نهایی'), ('VIEW', 'مشاهده'), ('EDIT', 'ویرایش'), ('CREATE', 'ایجاد'), ('DELETE', 'حذف'), ('SIGN_PAYMENT', 'امضای دستور پرداخت')], max_length=50, verbose_name='نوع اقدام')),
                ('entity_type', models.CharField(choices=[('FACTOR', 'فاکتور'), ('FACTORITEM', 'ردیف فاکتور'), ('TANKHAH', 'تنخواه'), ('BUDGET', 'بودجه'), ('PAYMENTORDER', 'دستور پرداخت'), ('REPORTS', 'گزارشات'), ('GENERAL', 'عمومی')], default='TANKHAH', max_length=50, verbose_name='نوع موجودیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('min_level', models.IntegerField(blank=True, null=True)),
                ('triggers_payment_order', models.BooleanField(default=False, verbose_name='فعال\u200cسازی دستور پرداخت')),
                ('allowed_actions', models.JSONField(default=list, verbose_name='اقدامات مجاز')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postactions', to='core.post', verbose_name='پست')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postactions', to='core.status', verbose_name='مرحله')),
            ],
            options={
                'verbose_name': 'اقدام مجاز پست',
                'verbose_name_plural': 'اقدامات مجاز پست\u200cها',
                'permissions': [('PostAction_view', 'نمایش اقدامات مجاز پست'), ('PostAction_add', 'افزودن اقدامات مجاز پست'), ('PostAction_update', 'بروزرسانی اقدامات مجاز پست'), ('PostAction_delete', 'حذف اقدامات مجاز پست')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام ساب\u200cپروژه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='بودجه تخصیص\u200cیافته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='core.project', verbose_name='پروژه اصلی')),
            ],
            options={
                'verbose_name': 'ساب\u200cپروژه',
                'verbose_name_plural': 'ساب\u200cپروژه\u200cها',
                'permissions': [('SubProject_add', 'افزودن زیر مجموعه پروژه'), ('SubProject_update', 'ویرایش زیر مجموعه پروژه'), ('SubProject_view', 'نمایش زیر مجموعه پروژه'), ('SubProject_delete', 'حــذف زیر مجموعه پروژه'), ('SubProject_Head_Office', 'تخصیص زیر مجموعه پروژه(دفتر مرکزی)🏠'), ('SubProject_Branch', 'تخصیص  زیر مجموعه پروژه(شعبه)🏠')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام/شرح گذار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.action', verbose_name='با اقدام')),
                ('allowed_posts', models.ManyToManyField(help_text='پست\u200cهایی که اجازه دارند این اقدام را در این وضعیت انجام دهند.', to='core.post', verbose_name='پست\u200cهای مجاز')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.entitytype', verbose_name='برای نوع موجودیت')),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions_from', to='core.status', verbose_name='از وضعیت')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='سازمان')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions_to', to='core.status', verbose_name='به وضعیت')),
            ],
            options={
                'verbose_name': 'گذار گردش کار',
                'verbose_name_plural': '۳. گذارهای گردش کار',
                'permissions': [('Transition_add', 'افزودن گذار گردش کار '), ('Transition_update', 'ویرایش گذار گردش کار '), ('Transition_view', 'نمایش گذار گردش کار '), ('Transition_delete', 'حــذف گذار گردش کار ')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TransitionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type_code', models.CharField(max_length=50, verbose_name='کد نوع موجودیت')),
                ('action_code', models.CharField(max_length=50, verbose_name='کد اقدام')),
                ('from_status_code', models.CharField(max_length=50, verbose_name='کد وضعیت مبدا')),
                ('to_status_code', models.CharField(max_length=50, verbose_name='کد وضعیت مقصد')),
                ('name_template', models.CharField(help_text='از {organization_name} برای نام سازمان استفاده کنید', max_length=255, verbose_name='تمپلیت نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'تمپلیت گذار',
                'verbose_name_plural': 'تمپلیت\u200cهای گذار',
                'permissions': [('TransitionTemplate_add', 'افزودن تمپلیت گذار'), ('TransitionTemplate_view', 'نمایش تمپلیت گذار'), ('TransitionTemplate_update', 'ویرایش تمپلیت گذار'), ('TransitionTemplate_delete', 'حذف تمپلیت گذار')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اتصال کاربر به پست',
                'verbose_name_plural': 'اتصالات کاربر به پست\u200cها',
                'permissions': [('UserPost_add', 'افزودن  اتصال کاربر به پست'), ('UserPost_update', 'بروزرسانی  اتصال کاربر به پست'), ('UserPost_view', 'نمایش   اتصال کاربر به پست'), ('UserPost_delete', 'حــذف  اتصال کاربر به پست')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserRuleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='فعال برای کاربر')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.action', verbose_name='اقدام')),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entitytype', verbose_name='نوع موجودیت')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='سازمان')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='پست (اختیاری)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فعال/غیرفعال قانون برای کاربر',
                'verbose_name_plural': 'فعال/غیرفعال قوانین برای کاربران',
                'permissions': [('UserRuleOverride_add', 'افزودن فعال/غیرفعال قانون برای کاربر'), ('UserRuleOverride_view', 'نمایش فعال/غیرفعال قانون برای کاربر'), ('UserRuleOverride_update', 'ویرایش فعال/غیرفعال قانون برای کاربر'), ('UserRuleOverride_delete', 'حذف فعال/غیرفعال قانون برای کاربر')],
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='entitytype',
            index=models.Index(fields=['code'], name='core_entity_code_18637a_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['code', 'org_type'], name='core_organi_code_eadc65_idx'),
        ),
        migrations.AddIndex(
            model_name='posthistory',
            index=models.Index(fields=['post', 'changed_at'], name='core_posthi_post_id_2c35ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postruleassignment',
            unique_together={('post', 'action', 'organization', 'entity_type')},
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['code'], name='core_status_code_d5fe62_idx'),
        ),
        migrations.AddIndex(
            model_name='transition',
            index=models.Index(fields=['entity_type', 'organization', 'from_status', 'is_active'], name='core_transi_entity__5109ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transition',
            unique_together={('organization', 'entity_type', 'from_status', 'action')},
        ),
        migrations.AlterUniqueTogether(
            name='transitiontemplate',
            unique_together={('entity_type_code', 'action_code')},
        ),
        migrations.AlterUniqueTogether(
            name='userruleoverride',
            unique_together={('user', 'organization', 'action', 'entity_type', 'post')},
        ),
    ]
