# Generated by Django 5.1.7 on 2025-03-20 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد سازمان')),
                ('name', models.CharField(max_length=100, verbose_name='نام سازمان')),
                ('org_type', models.CharField(choices=[('COMPLEX', 'مجتمع'), ('HQ', 'دفتر مرکزی')], max_length=10, verbose_name='نوع سازمان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'سازمان',
                'verbose_name_plural': 'سازمان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='TimeLockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_key', models.TextField(verbose_name='کلید قفل (رمزنگاری\u200cشده)')),
                ('hash_value', models.CharField(max_length=64, unique=True, verbose_name='هش مقدار تنظیم\u200cشده')),
                ('salt', models.CharField(max_length=32, unique=True, verbose_name='مقدار تصادفی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام مجموعه')),
            ],
            options={
                'verbose_name': 'قفل سیستم',
                'verbose_name_plural': 'قفل سیستم',
                'permissions': [('TimeLockModel_view', 'نمایش قفل سیستم'), ('TimeLockModel_add', 'افزودن قفل سیستم')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پست')),
                ('level', models.IntegerField(default=1, verbose_name='سطح')),
                ('branch', models.CharField(blank=True, choices=[('OPS', 'بهره\u200cبرداری'), ('FIN', 'مالی و اداری'), (None, 'بدون شاخه')], max_length=3, null=True, verbose_name='شاخه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='سازمان')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post', verbose_name='پست والد')),
            ],
            options={
                'verbose_name': 'پست سازمانی',
                'verbose_name_plural': 'پست\u200cهای سازمانی',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پروژه')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد پروژه')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('organizations', models.ManyToManyField(limit_choices_to={'org_type': 'COMPLEX'}, to='core.organization', verbose_name='مجتمع\u200cهای مرتبط')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اتصال کاربر به پست',
                'verbose_name_plural': 'اتصالات کاربر به پست\u200cها',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
