# Generated by Django 5.1.7 on 2025-09-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_action_without_org_chart',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، حتی بدون داشتن پست سازمانی هم اقدام ممکن است.', verbose_name='اجازه اقدام بدون رعایت پست\u200cها'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_bypass_org_chart',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، قوانین وابسته به پست/سطح می\u200cتوانند نادیده گرفته شوند.', verbose_name='اجازه دور زدن چارت سازمانی برای تأیید'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enforce_strict_approval_order',
            field=models.BooleanField(default=True, help_text='اگر فعال باشد، کاربر سطح بالاتر نمی\u200cتواند قبل از کاربر سطح پایین اقدام کند.', verbose_name='اجبار ترتیب سلسله\u200cمراتبی تأیید (سطح پایین قبل از سطح بالا)'),
        ),
    ]
