# Generated by Django 5.1.7 on 2025-04-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(limit_choices_to={'org_type__is_budget_allocatable': True}, to='core.organization', verbose_name='سازمان\u200cهای مرتبط'),
        ),
    ]
