# Generated by Django 5.0.6 on 2025-12-16 04:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='value_added_tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='درصد ارزش افزوده سراسری برای محاسبه در فاکتورها (مثلاً 9 برای 9%)', max_digits=5, verbose_name='درصد ارزش افزوده'),
        ),
        migrations.CreateModel(
            name='SystemSettingsValueAddedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='مقدار قبلی')),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='مقدار جدید')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تغییر')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده')),
            ],
            options={
                'verbose_name': 'لاگ تغییرات ارزش افزوده',
                'verbose_name_plural': 'لاگ\u200cهای تغییرات ارزش افزوده',
                'ordering': ['-changed_at'],
                'permissions': [('SystemSettingsValueAddedLog_view', 'نمایش لاگ تغییرات ارزش افزوده')],
                'default_permissions': (),
            },
        ),
    ]
