# Generated by Django 5.1.7 on 2025-04-05 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام ساب\u200cپروژه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='core.project', verbose_name='پروژه اصلی')),
            ],
            options={
                'verbose_name': 'ساب\u200cپروژه',
                'verbose_name_plural': 'ساب\u200cپروژه\u200cها',
                'permissions': [('SubProject_add', 'افزودن زیر مجموعه پروژه'), ('SubProject_update', 'ویرایش زیر مجموعه پروژه'), ('SubProject_view', 'نمایش زیر مجموعه پروژه'), ('SubProject_delete', 'حــذف زیر مجموعه پروژه')],
                'default_permissions': (),
            },
        ),
    ]
