# Generated by Django 5.1.7 on 2025-03-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeLockModel',
        ),
    ]
