# Generated by Django 5.1.7 on 2025-04-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationtype',
            name='name',
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='en_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='نام شعبه/مجتمع/اداره'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='fname',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='نام شعبه/مجتمع/اداره'),
        ),
    ]
