# Generated by Django 5.1.7 on 2025-10-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fontsettings',
            options={'ordering': ['-is_default', '-is_active', 'name'], 'permissions': [('FontSettingsـadd', 'افزودن تنظیمات فونت '), ('FontSettingsـview', 'نمایش تنظیمات فونت '), ('FontSettingsـupdate', 'بروزرسانی تنظیمات فونت '), ('FontSettingsـdelete', 'حذف تنظیمات فونت ')], 'verbose_name': 'تنظیمات فونت', 'verbose_name_plural': 'تنظیمات فونت\u200cها'},
        ),
    ]
