# Generated by Django 5.1.7 on 2025-09-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessrule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='accessrule',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='accessrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='accessrule',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='accessrule',
            name='post',
        ),
        migrations.AlterUniqueTogether(
            name='workflowruletemplate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workflowruletemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workflowruletemplate',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='postruleassignment',
            name='rule_template',
        ),
        migrations.DeleteModel(
            name='WorkflowStage',
        ),
    ]
