# Generated by Django 5.1.7 on 2025-06-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstage',
            name='triggers_payment_order',
            field=models.BooleanField(default=False, help_text='آیا این مرحله باعث ایجاد خودکار دستور پرداخت می\u200cشود؟ (برای تنخواه/فاکتور)', verbose_name='فعال\u200cسازی دستور پرداخت'),
        ),
    ]
