# Generated by Django 5.1.7 on 2025-09-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transition',
            unique_together={('organization', 'entity_type', 'from_status', 'action', 'to_status')},
        ),
    ]
