# Generated by Django 5.1.7 on 2025-09-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_is_admin_action_to_approval_log'),
        ('tankhah', '0002_add_is_admin_action_to_approval_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessRule',
        ),
        migrations.DeleteModel(
            name='WorkflowRuleTemplate',
        ),
    ]
