# Generated by Django 5.1.7 on 2025-04-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=80, unique=True, verbose_name='کد پروژه'),
        ),
    ]
