# Generated by Django 5.1.7 on 2025-10-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fontsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_tankhah_budget_overrun',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، در هنگام ثبت تنخواه/فاکتور، امکان ثبت مبلغ بیش از مانده تنخواه مجاز است.', verbose_name='اجازه ثبت بیش از بودجه تنخواه'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='lock_period_after_expiry_enforce_on_write_only',
            field=models.BooleanField(default=True, help_text='اگر فعال باشد، انقضای دوره باعث قفل سراسری نمی\u200cشود و فقط هنگام اقداماتی مثل ثبت تنخواه/تخصیص اعمال می\u200cگردد.', verbose_name='قفل دوره پس از انقضا فقط حین ثبت'),
        ),
    ]
