# Generated by Django 5.1.7 on 2025-04-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userpost_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationChartAPIView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('OrganizationChartAPIView_view', 'دسترسی به داشبورد چارت سازمانی 💻'), ('OrganizationChartView_view', '   دسترسی به گرافیک داشبورد چارت سازمانی 💻')],
                'default_permissions': (),
            },
        ),
    ]
