# Generated by Django 5.1.7 on 2025-09-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_update_transition_unique_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transition',
            unique_together=set(),
        ),
    ]
