# Generated by Django 5.1.7 on 2025-04-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_organizationtype_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationtype',
            old_name='en_name',
            new_name='org_type',
        ),
    ]
