# Generated by Django 5.1.7 on 2025-03-20 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_posthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'default_permissions': (), 'permissions': [('Organization_add', 'افزودن سازمان برای تعریف مجتمع\u200cها و دفتر مرکزی'), ('Organization_update', 'بروزرسانی سازمان برای تعریف مجتمع\u200cها و دفتر مرکزی'), ('Organization_delete', 'حــذف سازمان برای تعریف مجتمع\u200cها و دفتر مرکزی'), ('Organization_view', 'نمایش سازمان برای تعریف مجتمع\u200cها و دفتر مرکزی')], 'verbose_name': 'سازمان', 'verbose_name_plural': 'سازمان\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'default_permissions': (), 'permissions': [('Post_add', 'افزودن  پست سازمانی برای تعریف سلسله مراتب'), ('Post_update', 'بروزرسانی پست سازمانی برای تعریف سلسله مراتب'), ('Post_view', 'نمایش  پست سازمانی برای تعریف سلسله مراتب'), ('Post_delete', 'حــذف  پست سازمانی برای تعریف سلسله مراتب')], 'verbose_name': 'پست سازمانی', 'verbose_name_plural': 'پست\u200cهای سازمانی'},
        ),
        migrations.AlterModelOptions(
            name='posthistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'تاریخچه پست', 'verbose_name_plural': 'تاریخچه پست\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': (), 'permissions': [('Project_add', 'افزودن  پروژه برای مدیریت پروژه\u200cهای چندمجتمعی'), ('Project_update', 'بروزرسانی  پروژه برای مدیریت پروژه\u200cهای چندمجتمعی'), ('Project_view', 'نمایش  پروژه برای مدیریت پروژه\u200cهای چندمجتمعی'), ('Project_delete', 'حــذف  پروژه برای مدیریت پروژه\u200cهای چندمجتمعی')], 'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='userpost',
            options={'default_permissions': (), 'permissions': [('UserPost_add', 'افزودن  اتصال کاربر به پست'), ('UserPost_update', 'بروزرسانی  اتصال کاربر به پست'), ('UserPost_view', 'نمایش   اتصال کاربر به پست'), ('UserPost_delete', 'حــذف  اتصال کاربر به پست')], 'verbose_name': 'اتصال کاربر به پست', 'verbose_name_plural': 'اتصالات کاربر به پست\u200cها'},
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, help_text='زمان ثبت تغییر به صورت خودکار', verbose_name='تاریخ و زمان تغییر'),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='changed_by',
            field=models.ForeignKey(help_text='کاربری که این تغییر را اعمال کرده', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده'),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='changed_field',
            field=models.CharField(help_text='نام فیلدی که تغییر کرده (مثل name یا parent)', max_length=50, verbose_name='فیلد تغییر یافته'),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='new_value',
            field=models.TextField(blank=True, help_text='مقدار جدید فیلد بعد از تغییر', null=True, verbose_name='مقدار جدید'),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='old_value',
            field=models.TextField(blank=True, help_text='مقدار قبلی فیلد قبل از تغییر', null=True, verbose_name='مقدار قبلی'),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='post',
            field=models.ForeignKey(help_text='پستی که تغییر کرده است', on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='پست سازمانی'),
        ),
        migrations.AddIndex(
            model_name='posthistory',
            index=models.Index(fields=['post', 'changed_at'], name='core_posthi_post_id_2c35ae_idx'),
        ),
    ]
