# Generated by Django 5.1.7 on 2025-04-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_en_name_organizationtype_org_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtype',
            name='is_budget_allocatable',
            field=models.BooleanField(default=False, verbose_name='قابل استفاده برای تخصیص بودجه'),
        ),
    ]
