# Generated by Django 5.1.7 on 2025-04-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organizationchartapiview'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationChartView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('OrganizationChartView_view', '   دسترسی به گرافیک داشبورد چارت سازمانی 💻')],
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='organizationchartapiview',
            options={'default_permissions': (), 'permissions': [('OrganizationChartAPIView_view', 'دسترسی به داشبورد چارت سازمانی 💻')]},
        ),
    ]
