# Generated by Django 5.1.7 on 2025-09-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_is_admin_action_to_approval_log'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE core_postruleassignment DROP FOREIGN KEY core_postruleassignm_rule_template_id_00d25cb4_fk_core_work;
            ALTER TABLE core_postruleassignment DROP COLUMN rule_template_id;
            """,
            reverse_sql="""
            ALTER TABLE core_postruleassignment ADD COLUMN rule_template_id INT NULL;
            """
        ),
    ]
