# Generated by Django 5.1.7 on 2025-03-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_organization_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('COMPLEX', 'مجتمع'), ('COMPLEX', 'هتل'), ('COMPLEX', 'دفاتر استانی'), ('COMPLEX', 'مجموعه های استیجاری'), ('HQ', 'دفتر مرکزی')], max_length=10, verbose_name='نوع سازمان'),
        ),
    ]
