# Generated by Django 5.1.7 on 2025-04-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='max_change_level',
            field=models.IntegerField(default=1, help_text='حداکثر مرحله\u200cای که این پست می\u200cتواند تغییر دهد', verbose_name='حداکثر سطح تغییر'),
        ),
    ]
