# Generated by Django 5.0.6 on 2025-10-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsettings_allow_tankhah_budget_overrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_factor_budget_overrun',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، امکان ثبت مبلغ فاکتور بیش از مانده تنخواه مجاز است (مستقل از تنخواه).', verbose_name='اجازه ثبت بیش از بودجه فاکتور'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='factor_payment_ceiling_default',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='سقف پرداخت پیش\u200cفرض فاکتور'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='factor_payment_ceiling_enabled_default',
            field=models.BooleanField(default=False, verbose_name='فعال بودن پیش\u200cفرض سقف پرداخت فاکتور'),
        ),
    ]
