# Generated by Django 5.1.7 on 2025-09-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_transition_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicconfiguration',
            options={'default_permissions': (), 'ordering': ['category', 'key'], 'permissions': [('DynamicConfiguration_admin', 'پیکربندی پویای سیستم')], 'verbose_name': 'پیکربندی پویا', 'verbose_name_plural': 'پیکربندی\u200cهای پویا'},
        ),
    ]
