# Generated by Django 5.1.7 on 2025-04-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_max_change_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='max_change_level',
            field=models.IntegerField(default=1, help_text='حداکثر مرحله\u200cای که این پست می\u200cتواند تغییر دهد', verbose_name='حداکثر سطح تغییر(ارجاع به مرحله قبل تر)'),
        ),
    ]
