# Generated by Django 5.1.7 on 2025-03-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_organization_org_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('Dashboard_Core_view', 'دسترسی به داشبورد Core پایه')],
                'default_permissions': (),
            },
        ),
    ]
