# Generated by Django 4.2.7 on 2025-10-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsettings_allow_factor_budget_overrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enforce_tankhah_ceiling_on_factor',
            field=models.BooleanField(default=True, help_text='اگر فعال باشد، هنگام ثبت فاکتور، چک می\u200cشود که مبلغ فاکتور از سقف تنخواه تجاوز نکند.', verbose_name='اجبار سقف مبلغ در فرم فاکتور'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='exclude_expired_tankhah_from_factor_form',
            field=models.BooleanField(default=True, help_text='اگر فعال باشد، تنخواه\u200cهایی که due_date آن\u200cها گذشته است از dropdown فرم ایجاد فاکتور حذف می\u200cشوند.', verbose_name='حذف تنخواه\u200cهای منقضی\u200cشده از لیست فاکتور'),
        ),
    ]
