# Generated by Django 5.1.7 on 2025-04-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organizationchartview_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='postaction',
            name='entity_type',
            field=models.CharField(choices=[('TANKHAH', 'تنخواه'), ('BUDGET_ALLOCATION', 'تخصیص بودجه'), ('BUDGET_RETURN', 'تخصیص بودجه'), ('ISSUE_PAYMENT_ORDER', 'صدور دستور پرداخت')], default='TANKHAH', max_length=50, verbose_name='نوع موجودیت'),
        ),
        migrations.AlterField(
            model_name='postaction',
            name='action_type',
            field=models.CharField(choices=[('APPROVE', 'تأیید'), ('REJECT', 'رد'), ('FINALIZE', 'اتمام'), ('CUSTOM', 'سفارشی')], max_length=50, verbose_name='نوع اقدام'),
        ),
        migrations.AlterUniqueTogether(
            name='postaction',
            unique_together={('post', 'stage', 'action_type', 'entity_type')},
        ),
    ]
