# Generated by Django 5.0.6 on 2025-10-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsettings_enforce_tankhah_ceiling_on_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='create_budget_commitment_on_factor_draft',
            field=models.BooleanField(default=True, help_text='اگر فعال باشد، هنگام ثبت فاکتور، یک COMMITMENT در BudgetTransaction ایجاد می\u200cشود و بودجه رزرو می\u200cشود.', verbose_name='ایجاد تعهد بودجه هنگام ثبت فاکتور'),
        ),
    ]
