# Generated by Django 5.1.7 on 2025-10-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dashboardwidgetpermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enforce_single_browser_session',
            field=models.BooleanField(default=True, help_text='اگر فعال باشد، هر کاربر فقط یک سشن فعال در یک مرورگر خواهد داشت.', verbose_name='محدودیت به یک مرورگر (یک سشن)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enforce_single_tab',
            field=models.BooleanField(default=False, help_text='گزینه فرانت\u200cاندی برای جلوگیری از باز شدن همزمان چند تب (با localStorage/BroadcastChannel).', verbose_name='محدودیت به یک تب مرورگر'),
        ),
    ]
