# Generated by Django 5.1.7 on 2025-04-09 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_max_change_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='بودجه سالانه'),
        ),
        migrations.CreateModel(
            name='PostAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('APPROVE', 'تأیید'), ('REJECT', 'رد'), ('ISSUE_PAYMENT_ORDER', 'صدور دستور پرداخت'), ('FINALIZE', 'اتمام'), ('INSURANCE', 'ثبت بیمه'), ('CUSTOM', 'سفارشی')], max_length=50, verbose_name='نوع اقدام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='پست')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workflowstage', verbose_name='مرحله')),
            ],
            options={
                'verbose_name': 'اقدام مجاز پست',
                'verbose_name_plural': 'اقدامات مجاز پست\u200cها',
                'permissions': [('PostAction_view', 'نمایش اقدامات مجاز پست'), ('PostAction_add', 'افزودن اقدامات مجاز پست'), ('PostAction_update', 'بروزرسانی اقدامات مجاز پست'), ('PostAction_delete', 'حذف اقدامات مجاز پست')],
                'unique_together': {('post', 'stage', 'action_type')},
            },
        ),
    ]
