# Generated by Django 5.1.7 on 2025-03-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dashboard_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='بودجه (ريال)'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت فعال'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('HIGH', 'زیاد')], max_length=10, null=True, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='کد پروژه'),
        ),
    ]
