# Generated by Django 5.1.7 on 2025-04-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_organization_org_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_core',
            field=models.BooleanField(default=False, verbose_name='دفتر مرکزی سازمان'),
        ),
    ]
