# Generated by Django 5.1.7 on 2025-10-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemsettings_enforce_single_browser_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='heartbeat_interval_ms',
            field=models.IntegerField(default=3000, help_text='هر چند میلی\u200cثانیه یک\u200cبار تب فعال ضربان را ثبت کند؟ (پیشنهادی: 3000)', verbose_name='بازه ضربان تب (میلی\u200cثانیه)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='heartbeat_stale_ms',
            field=models.IntegerField(default=6000, help_text='اگر به مدت این مقدار ضربان ثبت نشود، تب دیگر می\u200cتواند مالکیت را بگیرد. (پیشنهادی: 6000)', verbose_name='مهلت منقضی شدن تب فعال (میلی\u200cثانیه)'),
        ),
    ]
