# Generated by Django 5.1.7 on 2025-04-09 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_budget_postaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization', verbose_name='سازمان والد'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_payment_order_signer',
            field=models.BooleanField(default=False, verbose_name='مجاز به امضای دستور پرداخت'),
        ),
    ]
