# Generated by Django 5.1.7 on 2025-03-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_budget_project_is_active_project_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مرحله')),
                ('order', models.IntegerField(verbose_name='ترتیب')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'مرحله گردش کار',
                'verbose_name_plural': 'مراحل گردش کار',
                'ordering': ['order'],
                'permissions': [('WorkflowStage_view', 'نمایش مرحله گردش کار'), ('WorkflowStage_add', 'افزودن مرحله گردش کار'), ('WorkflowStage_update', 'بروزرسانی مرحله گردش کار'), ('WorkflowStage_delete', 'حــذف مرحله گردش کار')],
                'default_permissions': (),
            },
        ),
    ]
