# Generated by Django 5.1.7 on 2025-04-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_alter_budgetperiod_name'),
        ('core', '0007_organization_parent_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': (), 'permissions': [('Project_add', 'افزودن پروژه برای مدیریت پروژه\u200cهای چندمجتمعی'), ('Project_update', 'بروزرسانی پروژه برای مدیریت پروژه\u200cهای چندمجتمعی'), ('Project_view', 'نمایش پروژه برای مدیریت پروژه\u200cهای چندمجتمعی'), ('Project_delete', 'حــذف پروژه برای مدیریت پروژه\u200cهای چندمجتمعی')], 'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه\u200cها'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='budget',
        ),
        migrations.AddField(
            model_name='project',
            name='allocations',
            field=models.ManyToManyField(blank=True, to='budgets.budgetallocation', verbose_name='تخصیص\u200cهای بودجه مرتبط'),
        ),
    ]
