# Generated by Django 5.1.7 on 2025-10-02 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemsettings_heartbeat_interval_ms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FontSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فونت')),
                ('family_name', models.CharField(help_text='نام CSS font-family', max_length=100, verbose_name='نام خانواده فونت')),
                ('font_file', models.FileField(upload_to='fonts/', verbose_name='فایل فونت')),
                ('font_format', models.CharField(choices=[('ttf', 'TrueType Font (.ttf)'), ('woff', 'Web Open Font Format (.woff)'), ('woff2', 'Web Open Font Format 2 (.woff2)'), ('eot', 'Embedded OpenType (.eot)'), ('otf', 'OpenType Font (.otf)')], max_length=10, verbose_name='فرمت فونت')),
                ('font_weight', models.IntegerField(choices=[(100, 'Thin'), (200, 'Extra Light'), (300, 'Light'), (400, 'Regular'), (500, 'Medium'), (600, 'Semi Bold'), (700, 'Bold'), (800, 'Extra Bold'), (900, 'Black')], default=400, verbose_name='وزن فونت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_default', models.BooleanField(default=False, verbose_name='فونت پیش\u200cفرض')),
                ('is_rtl_support', models.BooleanField(default=True, verbose_name='پشتیبانی از راست به چپ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آپلود شده توسط')),
            ],
            options={
                'verbose_name': 'تنظیمات فونت',
                'verbose_name_plural': 'تنظیمات فونت\u200cها',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
    ]
