# Generated by Django 5.1.7 on 2025-03-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workflowstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('COMPLEX', 'مجتمع'), ('HOTELS', 'هتل'), ('Provincial offices', 'دفاتر استانی'), ('Rental collections', 'مجموعه های استیجاری'), ('HQ', 'دفتر مرکزی')], max_length=25, verbose_name='نوع سازمان'),
        ),
    ]
