# Generated by Django 5.1.7 on 2025-03-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_organization_org_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('COMPLEX', 'مجتمع'), ('HOTEL', 'هتل'), ('PROVINCE', 'دفاتر استانی'), ('RENTAL', 'مجموعه\u200cهای استیجاری'), ('HQ', 'دفتر مرکزی')], max_length=25, verbose_name='نوع سازمان'),
        ),
    ]
