# Generated by Django 5.1.7 on 2025-04-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_project_options_remove_organization_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
    ]
