# Generated by Django 5.1.7 on 2025-03-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_organization_org_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('Dashboard__view', 'دسترسی به داشبورد اصلی ')],
                'default_permissions': (),
            },
        ),
    ]
