# Generated by Django 5.1.7 on 2025-04-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_alter_budgetperiod_name'),
        ('core', '0009_remove_project_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='allocations',
            field=models.ManyToManyField(blank=True, related_name='subprojects', to='budgets.budgetallocation', verbose_name='تخصیص\u200cهای بودجه'),
        ),
    ]
