# Generated by Django 5.1.7 on 2025-04-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subproject_allocations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subproject',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='allocations',
        ),
        migrations.AddField(
            model_name='subproject',
            name='allocated_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='بودجه تخصیص\u200cیافته'),
        ),
    ]
