# Generated by Django 5.1.7 on 2025-03-23 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dashboardview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardview',
            options={'default_permissions': (), 'permissions': [('Dashboard__view', 'دسترسی به داشبورد اصلی 💻')]},
        ),
    ]
