# Generated by Django 5.1.7 on 2025-04-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_project_options_alter_subproject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': (), 'permissions': [('Project_add', 'افزودن  مجموعه پروژه'), ('Project_update', 'ویرایش مجموعه پروژه'), ('Project_view', 'نمایش مجموعه پروژه'), ('Project_delete', 'حــذف مجموعه پروژه'), ('Project_Budget_allocation_Head_Office', 'تخصیص بودجه مجموعه پروژه(دفتر مرکزی)'), ('Project_Budget_allocation_Branch', 'تخصیص بودجه مجموعه پروژه(شعبه)')], 'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه'},
        ),
        migrations.AlterModelOptions(
            name='subproject',
            options={'default_permissions': (), 'permissions': [('SubProject_add', 'افزودن زیر مجموعه پروژه'), ('SubProject_update', 'ویرایش زیر مجموعه پروژه'), ('SubProject_view', 'نمایش زیر مجموعه پروژه'), ('SubProject_delete', 'حــذف زیر مجموعه پروژه'), ('SubProject_Budget_allocation_Head_Office', 'تخصیص بودجه زیر مجموعه پروژه(دفتر مرکزی)🏠'), ('SubProject_Budget_allocation_Branch', 'تخصیص بودجه زیر مجموعه پروژه(شعبه)🏠')], 'verbose_name': 'ساب\u200cپروژه', 'verbose_name_plural': 'ساب\u200cپروژه\u200cها'},
        ),
    ]
