# Generated by Django 5.1.7 on 2025-03-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_dashboardview_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardView_flows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('DashboardView_flows_view', 'دسترسی به روند تنخواه گردانی ')],
                'default_permissions': (),
            },
        ),
    ]
