# Generated by Django 5.1.7 on 2025-04-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0010_projectbudgetallocation'),
        ('core', '0012_alter_project_options_alter_subproject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': (), 'permissions': [('Project_add', 'افزودن  مجموعه پروژه'), ('Project_update', 'ویرایش مجموعه پروژه'), ('Project_view', 'نمایش مجموعه پروژه'), ('Project_delete', 'حــذف مجموعه پروژه')], 'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه'},
        ),
        migrations.AlterModelOptions(
            name='subproject',
            options={'default_permissions': (), 'permissions': [('SubProject_add', 'افزودن زیر مجموعه پروژه'), ('SubProject_update', 'ویرایش زیر مجموعه پروژه'), ('SubProject_view', 'نمایش زیر مجموعه پروژه'), ('SubProject_delete', 'حــذف زیر مجموعه پروژه'), ('SubProject_Head_Office', 'تخصیص زیر مجموعه پروژه(دفتر مرکزی)🏠'), ('SubProject_Branch', 'تخصیص  زیر مجموعه پروژه(شعبه)🏠')], 'verbose_name': 'ساب\u200cپروژه', 'verbose_name_plural': 'ساب\u200cپروژه\u200cها'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='allocations',
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='allocated_budget',
        ),
        migrations.AddField(
            model_name='subproject',
            name='allocations',
            field=models.ManyToManyField(blank=True, related_name='budget_allocations_set', to='budgets.projectbudgetallocation', verbose_name='تخصیص\u200cهای بودجه مرتبط'),
        ),
    ]
