# Generated by Django 5.1.7 on 2025-04-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_project_options_alter_subproject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='allocated_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='بودجه تخصیص\u200cیافته'),
        ),
    ]
