# Generated by Django 5.1.7 on 2025-10-06 08:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='شماره درخواست')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='سازمان')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project', verbose_name='پروژه')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='وضعیت')),
                ('subproject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subproject', verbose_name='زیرپروژه')),
            ],
            options={
                'verbose_name': 'درخواست کالا',
                'verbose_name_plural': 'درخواست\u200cهای کالا',
                'permissions': [('purchase_request_add', 'افزودن درخواست کالا'), ('purchase_request_view', 'نمایش درخواست کالا'), ('purchase_request_update', 'ویرایش درخواست کالا'), ('purchase_request_delete', 'حذف درخواست کالا'), ('purchase_request_approve', 'تأیید درخواست کالا')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='شرح')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=25, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='قیمت واحد')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='مبلغ')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_requests.purchaserequest', verbose_name='درخواست')),
            ],
        ),
    ]
