# Generated by Django 5.1.7 on 2025-10-06 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('purchase_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='external_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='شناسه خارجی'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='external_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='داده خام دریافتی/ارسالی'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='is_synced',
            field=models.BooleanField(default=False, verbose_name='همگام\u200cسازی شده'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='source_system',
            field=models.CharField(blank=True, max_length=100, verbose_name='سامانه منبع'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین همگام\u200cسازی'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='external_item_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='شناسه خارجی آیتم'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='sku',
            field=models.CharField(blank=True, max_length=100, verbose_name='شناسه کالا/کد فنی'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='uom',
            field=models.CharField(blank=True, max_length=50, verbose_name='واحد'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['number'], name='purchase_re_number_6001f3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['organization', 'date'], name='purchase_re_organiz_fbb6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['source_system', 'external_id'], name='purchase_re_source__d17c02_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestitem',
            index=models.Index(fields=['request'], name='purchase_re_request_c03fee_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestitem',
            index=models.Index(fields=['sku'], name='purchase_re_sku_414960_idx'),
        ),
    ]
