# Generated by Django 5.1.7 on 2025-10-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0002_purchaserequest_external_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequestitem',
            options={'default_permissions': (), 'permissions': [('purchase_request_item_add', 'افزودن ردیف درخواست کالا'), ('purchase_request_item_view', 'نمایش ردیف درخواست کالا'), ('purchase_request_item_update', 'ویرایش ردیف درخواست کالا'), ('purchase_request_item_delete', 'حذف ردیف درخواست کالا')], 'verbose_name': 'ردیف درخواست کالا', 'verbose_name_plural': 'ردیف\u200cهای درخواست کالا'},
        ),
    ]
