# Generated by Django 5.1.7 on 2025-05-31 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('core', '0001_initial'),
        ('tankhah', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettransaction',
            name='related_tankhah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tankhah.tankhah', verbose_name='تنخواه مرتبط'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='budget_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budgetallocation', verbose_name='تخصیص بودجه'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='payee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payees_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='created_by_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post', verbose_name='پست ایجادکننده'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to='core.workflowstage', verbose_name='مرحله فعلی'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders_organize', to='core.organization', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='پردازش توسط'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='budgets.payee', verbose_name='دریافت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='core.project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='related_factors',
            field=models.ManyToManyField(blank=True, related_name='payment_orders', to='tankhah.factor', verbose_name='فاکتورهای مرتبط '),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='related_tankhah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders_tankhah', to='tankhah.tankhah', verbose_name='تنخواه مرتبط'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='tankhah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='tankhah.tankhah', verbose_name='تنخواه'),
        ),
        migrations.AddField(
            model_name='projectbudgetallocation',
            name='budget_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_allocations', to='budgets.budgetallocation', verbose_name='تخصیص بودجه شعبه'),
        ),
        migrations.AddField(
            model_name='projectbudgetallocation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_budget_allocations_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='projectbudgetallocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='core.project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='projectbudgetallocation',
            name='subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='core.subproject', verbose_name='زیرپروژه'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_types_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetitem',
            unique_together={('budget_period', 'organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['budget_period', 'allocation_date'], name='budgets_bud_budget__3d5534_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['organization', 'allocated_amount'], name='budgets_bud_organiz_05ceb0_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbudgetallocation',
            index=models.Index(fields=['project'], name='budgets_pro_project_86d725_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbudgetallocation',
            index=models.Index(fields=['subproject'], name='budgets_pro_subproj_9a9505_idx'),
        ),
    ]
