# Generated by Django 5.1.7 on 2025-05-31 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='test',
        ),
    ]
