# Generated by Django 5.1.7 on 2025-09-25 08:56

import django.db.models.deletion
import django.utils.timezone
import version_tracker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(db_index=True, max_length=100)),
                ('version_number', models.CharField(db_index=True, max_length=20)),
                ('version_type', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('patch', 'Patch'), ('build', 'Build')], max_length=10)),
                ('release_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('code_hash', models.CharField(max_length=64)),
                ('changed_files', models.JSONField(default=list)),
                ('system_info', models.JSONField(default=dict)),
                ('major', models.PositiveIntegerField(default=0)),
                ('minor', models.PositiveIntegerField(default=0)),
                ('patch', models.PositiveIntegerField(default=0)),
                ('build', models.PositiveIntegerField(default=0)),
                ('is_final', models.BooleanField(default=False, verbose_name=' نسخه نهایی ')),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(default=version_tracker.models.get_default_author, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='version_tracker.appversion')),
            ],
            options={
                'verbose_name': 'نسخه بندی نرم افزار',
                'verbose_name_plural': 'نسخه بندی نرم افزار',
                'ordering': ['-major', '-minor', '-patch', '-build'],
                'permissions': [('ApplicationVersion_view', 'نمایش نسخه های نرم افزار'), ('ApplicationVersion_Update', 'بروزرسانی نسخه های نرم افزار'), ('ApplicationVersion_create', 'بروزرسانی نسخه های نرم افزار'), ('ApplicationVersion_delete', 'بروزرسانی نسخه های نرم افزار')],
                'default_permissions': (),
                'unique_together': {('app_name', 'major', 'minor', 'patch', 'build')},
            },
        ),
        migrations.CreateModel(
            name='BackupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مسیر')),
                ('path', models.CharField(max_length=500, verbose_name='مسیر')),
                ('location_type', models.CharField(choices=[('LOCAL', 'محلی'), ('NETWORK', 'شبکه'), ('CLOUD', 'ابر'), ('EXTERNAL', 'خارجی')], default='LOCAL', max_length=20, verbose_name='نوع مسیر')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال'), ('ERROR', 'خطا'), ('TESTING', 'در حال تست')], default='ACTIVE', max_length=20, verbose_name='وضعیت')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='رمزگذاری شده')),
                ('max_size_gb', models.IntegerField(blank=True, null=True, verbose_name='حداکثر حجم (GB)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('last_tested', models.DateTimeField(blank=True, null=True, verbose_name='آخرین تست')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='آخرین خطا')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'مسیر پشتیبان\u200cگیری',
                'verbose_name_plural': 'مسیرهای پشتیبان\u200cگیری',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, verbose_name='نسخه نهایی')),
                ('release_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('is_active', models.BooleanField(default=True)),
                ('app_versions', models.ManyToManyField(related_name='final_versions', to='version_tracker.appversion')),
            ],
            options={
                'verbose_name': 'نسخه نهایی',
                'verbose_name_plural': 'نسخه\u200cهای نهایی',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CodeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('change_type', models.CharField(choices=[('ADDED', 'اضافه شده'), ('MODIFIED', 'تغییر یافته'), ('DELETED', 'حذف شده')], max_length=20, verbose_name='نوع تغییر')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تغییر')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='version_tracker.appversion', verbose_name='نسخه')),
            ],
            options={
                'verbose_name': 'تغییر کد',
                'verbose_name_plural': 'تغییرات کد',
                'ordering': ['-change_date'],
                'permissions': [('CodeChangeLog_Add', 'افزودن تغییرات کد'), ('CodeChangeLog_View', 'نمایش تغییرات کد'), ('CodeChangeLog_Update', 'بروزرسانی تغییرات کد'), ('CodeChangeLog_delete', 'حــذف تغییرات کد')],
                'default_permissions': (),
                'unique_together': {('version', 'file_name')},
            },
        ),
        migrations.CreateModel(
            name='FileHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('hash_value', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('app_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_tracker.appversion')),
            ],
            options={
                'verbose_name': 'هش فایل',
                'verbose_name_plural': 'هش فایل کدها',
                'default_permissions': (),
                'unique_together': {('app_version', 'file_path')},
            },
        ),
    ]
