# Generated by Django 5.0.6 on 2025-02-21 16:47

import django.db.models.deletion
import django.utils.timezone
import version_tracker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appversion',
            options={'default_permissions': (), 'ordering': ['-major', '-minor', '-patch', '-build'], 'permissions': [('ApplicationVersion_view', 'نمایش نسخه های نرم افزار'), ('ApplicationVersion_Update', 'بروزرسانی نسخه های نرم افزار')], 'verbose_name': 'نسخه بندی نرم افزار', 'verbose_name_plural': 'نسخه بندی نرم افزار'},
        ),
        migrations.AddField(
            model_name='appversion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appversion',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name=' نسخه نهایی '),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='app_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='author',
            field=models.ForeignKey(default=version_tracker.models.get_default_author, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='changed_files',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='code_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='release_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='system_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='version_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='version_type',
            field=models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('patch', 'Patch'), ('build', 'Build')], max_length=10),
        ),
    ]
