# Generated by Django 5.1.7 on 2025-09-20 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مسیر')),
                ('path', models.CharField(max_length=500, verbose_name='مسیر')),
                ('location_type', models.CharField(choices=[('LOCAL', 'محلی'), ('NETWORK', 'شبکه'), ('CLOUD', 'ابر'), ('EXTERNAL', 'خارجی')], default='LOCAL', max_length=20, verbose_name='نوع مسیر')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال'), ('ERROR', 'خطا'), ('TESTING', 'در حال تست')], default='ACTIVE', max_length=20, verbose_name='وضعیت')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='رمزگذاری شده')),
                ('max_size_gb', models.IntegerField(blank=True, null=True, verbose_name='حداکثر حجم (GB)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('last_tested', models.DateTimeField(blank=True, null=True, verbose_name='آخرین تست')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='آخرین خطا')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'مسیر پشتیبان\u200cگیری',
                'verbose_name_plural': 'مسیرهای پشتیبان\u200cگیری',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
