# Generated by Django 5.0.6 on 2025-02-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_tracker', '0002_alter_appversion_options_appversion_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codechangelog',
            options={'default_permissions': (), 'ordering': ['-change_date'], 'verbose_name': 'تغییر کد', 'verbose_name_plural': 'تغییرات کد'},
        ),
        migrations.AlterModelOptions(
            name='filehash',
            options={'default_permissions': (), 'verbose_name': 'هش فایل', 'verbose_name_plural': 'هش فایل کدها'},
        ),
        migrations.AlterModelOptions(
            name='finalversion',
            options={'default_permissions': (), 'verbose_name': 'نسخه نهایی', 'verbose_name_plural': 'نسخه\u200cهای نهایی'},
        ),
    ]
