# Generated by Django 5.0.6 on 2025-02-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_tracker', '0003_alter_codechangelog_options_alter_filehash_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appversion',
            options={'default_permissions': (), 'ordering': ['-major', '-minor', '-patch', '-build'], 'permissions': [('ApplicationVersion_view', 'نمایش نسخه های نرم افزار'), ('ApplicationVersion_Update', 'بروزرسانی نسخه های نرم افزار'), ('ApplicationVersion_create', 'بروزرسانی نسخه های نرم افزار'), ('ApplicationVersion_delete', 'بروزرسانی نسخه های نرم افزار')], 'verbose_name': 'نسخه بندی نرم افزار', 'verbose_name_plural': 'نسخه بندی نرم افزار'},
        ),
        migrations.AlterModelOptions(
            name='codechangelog',
            options={'default_permissions': (), 'ordering': ['-change_date'], 'permissions': [('CodeChangeLog_Add', 'افزودن تغییرات کد'), ('CodeChangeLog_View', 'نمایش تغییرات کد'), ('CodeChangeLog_Update', 'بروزرسانی تغییرات کد'), ('CodeChangeLog_delete', 'حــذف تغییرات کد')], 'verbose_name': 'تغییر کد', 'verbose_name_plural': 'تغییرات کد'},
        ),
    ]
