# Generated by Django 5.1.7 on 2025-09-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofile',
            name='custom_theme_data',
            field=models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای تم سفارشی'),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='theme',
            field=models.CharField(choices=[('default', 'پیش\u200cفرض'), ('light', 'روشن'), ('dark', 'تاریک'), ('blue', 'آبی'), ('green', 'سبز'), ('ocean', 'اقیانوس'), ('sunset', 'غروب'), ('forest', 'جنگل'), ('purple', 'بنفش'), ('midnight', 'نیمه\u200cشب'), ('mint', 'نعنایی'), ('warm', 'گرم'), ('vibrant', 'زنده'), ('deep', 'عمیق'), ('tropical', 'استوایی'), ('custom', 'سفارشی')], default='default', max_length=20),
        ),
    ]
