# Generated by Django 5.1.7 on 2025-03-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customprofile',
            options={'default_permissions': [], 'permissions': [('users_view_userprofile', 'می\u200cتواند پروفایل کاربران را مشاهده کند'), ('users_add_userprofile', 'می\u200cتواند پروفایل کاربری اضافه دهد'), ('users_update_userprofile', 'می\u200cتواند پروفایل کاربر را تغییر دهد'), ('users_delete_userprofile', 'می\u200cتواند پروفایل کاربر را غیرفعال کرد'), ('users_Search_userprofile', 'می\u200cتواند پروفایل کاربر را جستجو کند')], 'verbose_name': 'ساخت پروفایل سفارشی', 'verbose_name_plural': 'ساخت پروفایل سفارشی'},
        ),
    ]
