# Generated by Django 5.1.7 on 2025-03-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'روشن'), ('dark', 'تاریک'), ('blue', 'آبی'), ('green', 'سبز')], default='light', max_length=20),
        ),
    ]
