# Generated by Django 5.1.7 on 2025-09-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customprofile_custom_theme_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='theme',
            field=models.CharField(choices=[], default='default', max_length=20),
        ),
    ]
