# Generated by Django 5.1.7 on 2025-04-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customprofile',
            options={'default_permissions': [], 'permissions': [('users_view_userprofile', 'می\u200cتواند پروفایل کاربران را مشاهده کند'), ('users_add_userprofile', 'می\u200cتواند پروفایل کاربری اضافه کند'), ('users_update_userprofile', 'می\u200cتواند پروفایل کاربر را تغییر دهد'), ('users_delete_userprofile', 'می\u200cتواند پروفایل کاربر را غیرفعال کند'), ('users_search_userprofile', 'می\u200cتواند پروفایل کاربر را جستجو کند')], 'verbose_name': 'پروفایل سفارشی', 'verbose_name_plural': 'پروفایل\u200cهای سفارشی'},
        ),
    ]
