# Generated by Django 5.1.7 on 2025-04-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tankhah', '0009_tankhah_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='مبلغ کل')),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='مبلغ تأییدشده')),
                ('rejected_amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='مبلغ ردشده')),
                ('payment_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پرداخت')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ گزارش')),
                ('tankhah', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tankhah.tankhah', verbose_name='تنخواه')),
            ],
        ),
    ]
