# Generated by Django 5.1.7 on 2025-08-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='مبلغ کل')),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='مبلغ تأییدشده')),
                ('rejected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='مبلغ ردشده')),
                ('payment_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پرداخت')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ گزارش')),
                ('last_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='ردیابی تغییرات وضعیت')),
                ('total_factors', models.IntegerField(default=0, verbose_name='تعداد کل فاکتورها')),
                ('approved_factors', models.IntegerField(default=0, verbose_name='تعداد فاکتورهای تأییدشده')),
                ('rejected_factors', models.IntegerField(default=0, verbose_name='تعداد فاکتورهای ردشده')),
            ],
            options={
                'verbose_name': 'گزارش مالی',
                'verbose_name_plural': 'گزارش\u200cهای مالی',
                'permissions': [('FinancialReport_view', 'نمایش گزارشات جامع مالی ♻️'), ('FinancialReport_add', 'افزودن گزارشات جامع مالی ♻️'), ('FinancialReport_update', 'ویرایش گزارشات جامع مالی ♻️'), ('FinancialReport_delet', 'حــذف گزارشات جامع مالی ♻️')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='print_financial_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'امکان چاپ گزارش ',
                'verbose_name_plural': 'امکان چاپ گزارش ',
                'permissions': [('print_financial_report_view', 'امکان چاپ گزارش ')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='send_to_accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'گزارشات تنخواه نهایی شده',
                'verbose_name_plural': 'گزارشات تنخواه نهایی شده',
                'permissions': [('send_to_accounting_report_view', 'امکان ارسال گزارش ')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Tankhah_FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'گزارشات تنخواه نهایی شده',
                'verbose_name_plural': 'گزارشات تنخواه نهایی شده',
                'permissions': [('Tankhah_FinancialReport_view', 'امکان نمایش گزارشات تنخواه نهایی شده')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TankhahDetailView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'گزارش جزئیات تنخواه\u200cها',
                'verbose_name_plural': 'گزارش جزئیات تنخواه\u200cها',
                'permissions': [('TankhahDetailView_report_view', 'گزارش جزئیات تنخواه\u200cها ')],
                'default_permissions': (),
            },
        ),
    ]
