# Generated by Django 4.2.7 on 2025-11-17 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tankhah', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='tankhah',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tankhah.tankhah', verbose_name='تنخواه'),
        ),
    ]
