# Generated by Django 5.1.7 on 2025-09-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsAPIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'API های گزارشات',
                'verbose_name_plural': 'API های گزارشات',
                'permissions': [('reports.api_dashboard_data', 'دسترسی به API داده\u200cهای داشبورد'), ('reports.api_organizations', 'دسترسی به API سازمان\u200cها'), ('reports.api_projects', 'دسترسی به API پروژه\u200cها'), ('reports.api_budget_periods', 'دسترسی به API دوره\u200cهای بودجه'), ('reports.api_export_data', 'دسترسی به API صادرات داده')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReportsDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'داشبورد گزارشات',
                'verbose_name_plural': 'داشبورد گزارشات',
                'permissions': [('reports.view_dashboard', 'نمایش داشبورد گزارشات'), ('reports.view_analytics', 'نمایش تحلیل\u200cهای پیشرفته'), ('reports.export_reports', 'صادرات گزارشات'), ('reports.view_executive_dashboard', 'نمایش داشبورد اجرایی')],
                'default_permissions': (),
            },
        ),
    ]
