# Generated by Django 5.1.7 on 2025-10-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportsapis_reportsdashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialreport',
            options={'default_permissions': (), 'permissions': [('FinancialReport_view', 'نمایش گزارشات جامع مالی ♻️'), ('FinancialReport_add', 'افزودن گزارشات جامع مالی ♻️'), ('FinancialReport_update', 'ویرایش گزارشات جامع مالی ♻️'), ('FinancialReport_delet', 'حــذف گزارشات جامع مالی ♻️'), ('view_comprehensive_budget_report', 'نمایش گزارش جامع بودجه')], 'verbose_name': 'گزارش مالی', 'verbose_name_plural': 'گزارش\u200cهای مالی'},
        ),
    ]
