# Generated by Django 5.1.7 on 2025-08-05 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0004_alter_contenttype_id'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=100, verbose_name='فعل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('unread', models.BooleanField(default=True, verbose_name='خوانده\u200cنشده')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف\u200cشده')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('priority', models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('HIGH', 'زیاد'), ('WARNING', 'هشدار'), ('ERROR', 'خطا'), ('LOCKED', 'قفل\u200cشده')], default='MEDIUM', max_length=20, verbose_name='اولویت')),
                ('entity_type', models.CharField(choices=[('FACTOR', 'فاکتور'), ('TANKHAH', 'تنخواه'), ('PAYMENTORDER', 'دستور پرداخت')], max_length=50, verbose_name='نوع موجودیت')),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه هدف')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_notifications', to=settings.AUTH_USER_MODEL, verbose_name='عامل')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع هدف')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-timestamp'],
                'permissions': [('Notification_view', 'نمایش اعلان'), ('Notification_delete', 'حذف اعلان')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('FACTOR', 'فاکتور'), ('TANKHAH', 'تنخواه'), ('PAYMENTORDER', 'دستور پرداخت')], max_length=50, verbose_name='نوع موجودیت')),
                ('action', models.CharField(choices=[('CREATED', 'ایجاد'), ('APPROVED', 'تأیید'), ('REJECTED', 'رد'), ('PAID', 'پرداخت')], max_length=50, verbose_name='اقدام')),
                ('priority', models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('HIGH', 'زیاد')], default='MEDIUM', max_length=20, verbose_name='اولویت')),
                ('channel', models.CharField(choices=[('IN_APP', 'درون\u200cبرنامه'), ('EMAIL', 'ایمیل'), ('SMS', 'پیامک')], default='IN_APP', max_length=50, verbose_name='کانال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('recipients', models.ManyToManyField(to='core.post', verbose_name='گیرندگان')),
            ],
            options={
                'verbose_name': 'قانون اعلان',
                'verbose_name_plural': 'قوانین اعلان',
                'permissions': [('NotificationRule_add', 'افزودن اعلان'), ('NotificationRule_update', 'بروزرسانی اعلان'), ('NotificationRule_view', 'نمایش اعلان'), ('NotificationRule_delete', 'حذف اعلان')],
                'default_permissions': (),
            },
        ),
    ]
