# Generated by Django 5.1.7 on 2025-09-20 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity_type',
            field=models.CharField(choices=[('FACTOR', 'فاکتور'), ('TANKHAH', 'تنخواه'), ('PAYMENTORDER', 'دستور پرداخت'), ('BACKUP', 'پشتیبان\u200cگیری'), ('SYSTEM', 'سیستم'), ('SECURITY', 'امنیت'), ('MAINTENANCE', 'نگهداری')], max_length=50, verbose_name='نوع موجودیت'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='action',
            field=models.CharField(choices=[('CREATED', 'ایجاد'), ('APPROVED', 'تأیید'), ('REJECTED', 'رد'), ('PAID', 'پرداخت'), ('COMPLETED', 'تکمیل'), ('FAILED', 'ناموفق'), ('SCHEDULED', 'زمان\u200cبندی شده'), ('STARTED', 'شروع شده'), ('FINISHED', 'پایان یافته')], max_length=50, verbose_name='اقدام'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='entity_type',
            field=models.CharField(choices=[('FACTOR', 'فاکتور'), ('TANKHAH', 'تنخواه'), ('PAYMENTORDER', 'دستور پرداخت'), ('BACKUP', 'پشتیبان\u200cگیری'), ('SYSTEM', 'سیستم'), ('SECURITY', 'امنیت'), ('MAINTENANCE', 'نگهداری')], max_length=50, verbose_name='نوع موجودیت'),
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام اسکچول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('frequency', models.CharField(choices=[('DAILY', 'روزانه'), ('WEEKLY', 'هفتگی'), ('MONTHLY', 'ماهانه'), ('CUSTOM', 'سفارشی')], max_length=20, verbose_name='فرکانس')),
                ('custom_cron', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cron سفارشی')),
                ('database', models.CharField(choices=[('BOTH', 'هر دو دیتابیس'), ('MAIN', 'دیتابیس اصلی'), ('LOGS', 'دیتابیس لاگ')], default='BOTH', max_length=10, verbose_name='دیتابیس')),
                ('format_type', models.CharField(choices=[('JSON', 'JSON'), ('SQL', 'SQL')], default='JSON', max_length=10, verbose_name='فرمت')),
                ('encrypt', models.BooleanField(default=False, verbose_name='رمزگذاری')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='رمز عبور')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخرین اجرا')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='اجرای بعدی')),
                ('notify_on_success', models.BooleanField(default=True, verbose_name='اعلان در صورت موفقیت')),
                ('notify_on_failure', models.BooleanField(default=True, verbose_name='اعلان در صورت خطا')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('notify_recipients', models.ManyToManyField(related_name='backup_schedules', to=settings.AUTH_USER_MODEL, verbose_name='گیرندگان اعلان')),
            ],
            options={
                'verbose_name': 'اسکچول پشتیبان\u200cگیری',
                'verbose_name_plural': 'اسکچول\u200cهای پشتیبان\u200cگیری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STARTED', 'شروع شده'), ('COMPLETED', 'تکمیل شده'), ('FAILED', 'ناموفق'), ('CANCELLED', 'لغو شده')], max_length=20, verbose_name='وضعیت')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='مدت زمان')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='حجم فایل')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='مسیر فایل')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notificationApp.backupschedule', verbose_name='اسکچول')),
            ],
            options={
                'verbose_name': 'لاگ پشتیبان\u200cگیری',
                'verbose_name_plural': 'لاگ\u200cهای پشتیبان\u200cگیری',
                'ordering': ['-started_at'],
            },
        ),
    ]
