# Generated by Django 5.1.7 on 2025-09-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0002_alter_backupschedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupschedule',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('BackupSchedule_admin', 'مدیریت پشتیبان گیری'), ('BackupSchedule_view', 'نمایش پشتیبان ها '), ('BackupSchedule_delete', 'نمایش پشتیبان ها '), ('BackupSchedule_create', 'نمایش پشتیبان ها ')], 'verbose_name': 'اسکچول پشتیبان\u200cگیری', 'verbose_name_plural': 'اسکچول\u200cهای پشتیبان\u200cگیری'},
        ),
    ]
