# Generated by Django 5.1.7 on 2025-06-03 09:15

import django.db.models.deletion
import django.utils.timezone
import tankhah.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('contenttypes', '0004_alter_contenttype_id'),
        ('core', '0002_alter_workflowstage_triggers_payment_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_Tankhah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('Dashboard_Tankhah_view', 'دسترسی به داشبورد تنخواه گردان ')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('min_stage_order', models.IntegerField(default=1, verbose_name='حداقل ترتیب مرحله')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته بندی نوع هزینه کرد',
                'verbose_name_plural': 'دسته بندی نوع هزینه کرد',
                'permissions': [('ItemCategory_add', 'افزودن دسته بندی نوع هزینه کرد'), ('ItemCategory_update', 'ویرایش دسته بندی نوع هزینه کرد'), ('ItemCategory_view', 'نمایش دسته بندی نوع هزینه کرد'), ('ItemCategory_delete', 'حــذف دسته بندی نوع هزینه کرد')],
            },
        ),
        migrations.CreateModel(
            name='TankhActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=25, verbose_name='انواع  اقدام')),
            ],
            options={
                'verbose_name': 'انواع اقدام',
                'verbose_name_plural': 'انواع اقدام ',
                'permissions': [('TankhActionType_add', 'افزودن نوع اقدام'), ('TankhActionType_view', 'نمایش نوع اقدام'), ('TankhActionType_update', 'ویرایش نوع اقدام'), ('TankhActionType_delete', 'حذف نوع اقدام')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TankhahFinalApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('TankhahFinalApproval_view', 'دسترسی تایید یا رد تنخواه گردان ')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='شماره فاکتور')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='مبلغ فاکتور')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING', 'در انتظار تأیید'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده'), ('PAID', 'پرداخت شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='نهایی شده')),
                ('locked', models.BooleanField(default=False, verbose_name='قفل شده')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='بودجه تخصیصی')),
                ('remaining_budget', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='بودجه باقیمانده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='اضطراری')),
                ('is_locked', models.BooleanField(default=False, verbose_name='قفل شود')),
                ('approved_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='تأییدکنندگان')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CustomUser_related', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('locked_by_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workflowstage', verbose_name='قفل شده توسط مرحله')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tankhah.itemcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'permissions': [('factor_add', 'افزودن فاکتور'), ('factor_view', 'نمایش فاکتور'), ('factor_update', 'بروزرسانی فاکتور'), ('factor_delete', 'حذف فاکتور'), ('factor_approve', 'تأیید فاکتور'), ('factor_reject', 'رد فاکتور'), ('Factor_full_edit', 'دسترسی کامل به فاکتور'), ('factor_unlock', 'باز کردن فاکتور قفل\u200cشده')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FactorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tankhah.models.factor_document_upload_path, verbose_name='فایل پیوست')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tankhah.factor', verbose_name='فاکتور')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آپلود شده توسط')),
            ],
            options={
                'verbose_name': 'سند فاکتور',
                'verbose_name_plural': 'اسناد فاکتور',
                'permissions': [('FactorDocument_add', 'افزودن سند فاکتور'), ('FactorDocument_update', 'بروزرسانی سند فاکتور'), ('FactorDocument_view', 'نمایش سند فاکتور'), ('FactorDocument_delete', 'حــذف سند فاکتور')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FactorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('CREATION', 'ایجاد'), ('UPDATE', 'ویرایش'), ('STATUS_CHANGE', 'تغییر وضعیت'), ('DELETION', 'حذف')], max_length=20, verbose_name='نوع تغییر')),
                ('change_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان تغییر')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای قبلی')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای جدید')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تغییر توسط')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tankhah.factor', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'تاریخچه فاکتور',
                'verbose_name_plural': 'تاریخچه\u200cهای فاکتور',
                'ordering': ['-change_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FactorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='شرح ردیف')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('PENDING', 'در حال بررسی'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده'), ('PAID', 'پرداخت شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=25, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='قیمت واحد')),
                ('min_stage_order', models.IntegerField(default=1, editable=False, help_text='این نوع تراکنش فقط در این مرحله یا بالاتر مجاز است', verbose_name='حداقل ترتیب مرحله')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین ویرایش')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tankhah.factor', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'ردیف فاکتور',
                'verbose_name_plural': 'ردیف\u200cهای فاکتور',
                'ordering': ['factor', 'pk'],
                'permissions': [('FactorItem_add', 'افزودن ردیف فاکتور'), ('FactorItem_update', 'ویرایش ردیف فاکتور'), ('FactorItem_view', 'نمایش ردیف فاکتور'), ('FactorItem_delete', 'حذف ردیف فاکتور'), ('FactorItem_approve', 'تأیید ردیف فاکتور'), ('FactorItem_reject', 'رد ردیف فاکتور')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StageApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('entity_type', models.CharField(choices=[('TANKHAH', 'تنخواه'), ('BUDGET_ALLOCATION', 'تخصیص بودجه')], default='TANKHAH', max_length=50, verbose_name='نوع موجودیت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='پست مجاز')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workflowstage', verbose_name='مرحله')),
            ],
            options={
                'verbose_name': 'تأییدکننده مرحله',
                'verbose_name_plural': 'تأییدکنندگان مرحله',
                'permissions': [('stageapprover__view', 'نمایش تأییدکننده مرحله'), ('stageapprover__add', 'افزودن تأییدکننده مرحله'), ('stageapprover__Update', 'بروزرسانی تأییدکننده مرحله'), ('stageapprover__delete', 'حــذف تأییدکننده مرحله')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Tankhah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=150, unique=True, verbose_name='شماره تنخواه')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='مبلغ')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='مهلت زمانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('letter_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره نامه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING', 'در حال بررسی'), ('APPROVED', 'تأییدشده'), ('SENT_TO_HQ', 'ارسال\u200cشده به HQ'), ('HQ_OPS_PENDING', 'در حال بررسی - بهره\u200cبرداری'), ('HQ_OPS_APPROVED', 'تأییدشده - بهره\u200cبرداری'), ('HQ_FIN_PENDING', 'در حال بررسی - مالی'), ('PAID', 'پرداخت\u200cشده'), ('REJECTED', 'ردشده')], default='DRAFT', max_length=20, verbose_name='وضعیت')),
                ('hq_status', models.CharField(blank=True, choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING', 'در حال بررسی'), ('APPROVED', 'تأییدشده'), ('SENT_TO_HQ', 'ارسال\u200cشده به HQ'), ('HQ_OPS_PENDING', 'در حال بررسی - بهره\u200cبرداری'), ('HQ_OPS_APPROVED', 'تأییدشده - بهره\u200cبرداری'), ('HQ_FIN_PENDING', 'در حال بررسی - مالی'), ('PAID', 'پرداخت\u200cشده'), ('REJECTED', 'ردشده')], max_length=20, null=True, verbose_name='وضعیت در HQ')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آرشیو شده')),
                ('payment_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پرداخت')),
                ('is_locked', models.BooleanField(default=False, verbose_name='قفل شده')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان آرشیو')),
                ('canceled', models.BooleanField(default=False, verbose_name='لغو شده')),
                ('remaining_budget', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='بودجه باقیمانده')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='اضطراری')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ درخواست')),
                ('payment_ceiling', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='سقف پرداخت')),
                ('is_payment_ceiling_enabled', models.BooleanField(default=False, verbose_name='فعال بودن سقف پرداخت')),
                ('approved_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='تأییدکنندگان')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tankhah_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('current_stage', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workflowstage', verbose_name='مرحله فعلی')),
                ('last_stopped_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post', verbose_name='آخرین پست متوقف\u200cشده')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='مجموعه/شعبه')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tankhah_set', to='core.project', verbose_name='پروژه')),
                ('project_budget_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tankhahs', to='budgets.BudgetAllocation', verbose_name='تخصیص بودجه پروژه')),
                ('subproject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subproject', verbose_name='زیر مجموعه پروژه')),
            ],
            options={
                'verbose_name': 'تنخواه',
                'verbose_name_plural': 'تنخواه\u200cها',
                'permissions': [],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='factor',
            name='tankhah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='tankhah.tankhah', verbose_name='تنخواه'),
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVE', 'تأیید'), ('REJECT', 'رد'), ('STAGE_CHANGE', 'تغییر مرحله'), ('NONE', 'هیچکدام')], max_length=25, verbose_name='اقدام')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('changed_field', models.CharField(blank=True, max_length=50, null=True, verbose_name='فیلد تغییر یافته')),
                ('seen_by_higher', models.BooleanField(default=False, verbose_name='دیده\u200cشده توسط رده بالاتر')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان دیده شدن')),
                ('action_type', models.CharField(blank=True, max_length=50, verbose_name='نوع اقدام')),
                ('object_id', models.PositiveIntegerField(verbose_name='شناسه موجودیت')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع موجودیت')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post', verbose_name='پست تأییدکننده')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workflowstage', verbose_name='مرحله')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='tankhah.factor', verbose_name='فاکتور')),
                ('factor_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='tankhah.factoritem', verbose_name='ردیف فاکتور')),
                ('tankhah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='tankhah.tankhah', verbose_name='تنخواه')),
            ],
            options={
                'verbose_name': 'تأیید',
                'verbose_name_plural': 'تأییدات👍',
                'permissions': [('Approval_add', 'افزودن تأیید برای ثبت اقدامات تأیید یا رد '), ('Approval_update', 'ویرایش تأیید برای ثبت اقدامات تأیید یا رد'), ('Approval_delete', 'حــذف تأیید برای ثبت اقدامات تأیید یا رد'), ('Approval_view', 'نمایش تأیید برای ثبت اقدامات تأیید یا رد')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TankhahAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='مبلغ (برای پرداخت)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='شماره مرجع')),
                ('action_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgets.transactiontype', verbose_name='نوع اقدام')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post', verbose_name='پست انجام\u200cدهنده')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workflowstage', verbose_name='مرحله')),
                ('tankhah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='tankhah.tankhah', verbose_name='تنخواه')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اقدام تنخواه',
                'verbose_name_plural': 'اقدامات تنخواه',
                'permissions': [('TankhahAction_view', 'نمایش اقدامات تنخواه'), ('TankhahAction_add', 'افزودن اقدامات تنخواه'), ('TankhahAction_update', 'بروزرسانی اقدامات تنخواه'), ('TankhahAction_delete', 'حذف اقدامات تنخواه')],
            },
        ),
        migrations.CreateModel(
            name='TankhahDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=tankhah.models.tankhah_document_path, verbose_name='سند')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('tankhah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tankhah.tankhah', verbose_name='تنخواه')),
            ],
            options={
                'permissions': [('TankhahDocument_view', 'نمایش اسناد فاکتور منتهی به تنخواه'), ('TankhahDocument_add', 'افزودن اسناد فاکتور منتهی به تنخواه'), ('TankhahDocument_update', 'بروزرسانی اسناد فاکتور منتهی به تنخواه'), ('TankhahDocument_delete', 'حــذف اسناد فاکتور منتهی به تنخواه')],
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='factoritem',
            index=models.Index(fields=['factor', 'status'], name='tankhah_fac_factor__8a81a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stageapprover',
            unique_together={('stage', 'post', 'entity_type')},
        ),
        migrations.AddIndex(
            model_name='tankhah',
            index=models.Index(fields=['number', 'date', 'status', 'organization'], name='tankhah_tan_number_dd4c50_idx'),
        ),
        migrations.AddIndex(
            model_name='factor',
            index=models.Index(fields=['number', 'date', 'status', 'tankhah'], name='tankhah_fac_number_940511_idx'),
        ),
    ]
