# Generated by Django 5.1.7 on 2025-06-05 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
        ('core', '0002_alter_workflowstage_triggers_payment_order'),
        ('tankhah', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tankhah',
            options={'default_permissions': (), 'permissions': [('Tankhah_add', ' + افزودن تنخواه'), ('Tankhah_view', 'نمایش تنخواه'), ('Tankhah_detail', 'نمایش تنخواه'), ('Tankhah_update', '🆙بروزرسانی تنخواه'), ('Tankhah_delete', '⛔حذف تنخواه'), ('Tankhah_approve', '👍تأیید تنخواه'), ('Tankhah_reject', 'رد تنخواه👎'), ('Tankhah_view_all', 'نمایش همه تنخواه\u200cها (دفتر مرکزی)'), ('Tankhah_part_approve', '👍تأیید رئیس قسمت'), ('Tankhah_hq_view', 'رصد دفتر مرکزی'), ('Tankhah_hq_approve', '👍تأیید رده بالا در دفتر مرکزی'), ('Tankhah_HQ_OPS_PENDING', 'در حال بررسی - بهره\u200cبرداری'), ('Tankhah_HQ_OPS_APPROVED', '👍تأییدشده - بهره\u200cبرداری'), ('Tankhah_HQ_FIN_PENDING', 'در حال بررسی - مالی'), ('Tankhah_PAID', 'پرداخت\u200cشده'), ('FactorItem_approve', '👍تایید/رد ردیف فاکتور (تایید ردیف فاکتور*استفاده در مراحل تایید*)'), ('edit_full_tankhah', '👍😊تغییرات کاربری در فاکتور /تایید یا رد ردیف ها '), ('Dashboard_Core_view', 'دسترسی به داشبورد Core پایه'), ('DashboardView_flows_view', 'دسترسی به روند تنخواه گردانی'), ('Dashboard__view', 'دسترسی به داشبورد اصلی 💻'), ('Dashboard_Stats_view', 'دسترسی به آمار کلی داشبورد💲')], 'verbose_name': 'تنخواه', 'verbose_name_plural': 'تنخواه\u200cها'},
        ),
        migrations.RemoveIndex(
            model_name='tankhah',
            name='tankhah_tan_number_dd4c50_idx',
        ),
        migrations.AddIndex(
            model_name='tankhah',
            index=models.Index(fields=['number', 'date', 'status', 'organization', 'number', 'project_id', 'organization_id', 'status', 'created_at'], name='tankhah_tan_number_03dabf_idx'),
        ),
    ]
