# Generated by Django 5.1.7 on 2025-10-06 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0001_initial'),
        ('tankhah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factors', to='purchase_requests.purchaserequest', verbose_name='درخواست کالا'),
        ),
    ]
