# Generated by Django 5.1.7 on 2025-04-11 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankhah',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ درخواست'),
        ),
    ]
