# Generated by Django 5.1.7 on 2025-04-05 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subproject'),
        ('tankhah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankhah',
            name='subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subproject', verbose_name='زیر مجموعه پروژه'),
        ),
    ]
