# Generated by Django 5.1.7 on 2025-04-20 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0004_alter_contenttype_id'),
        ('core', '0005_alter_postaction_unique_together_and_more'),
        ('tankhah', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tankhah',
            options={'default_permissions': (), 'permissions': [('Tankhah_add', 'ثبت تنخواه'), ('Tankhah_update', 'بروزرسانی تنخواه'), ('Tankhah_view', 'نمایش تنخواه'), ('Tankhah_delete', 'حذف تنخواه'), ('Tankhah_part_approve', '👍تأیید رئیس قسمت'), ('Tankhah_approve', '👍  \u200cتواند تنخواه را تأیید کند'), ('Tankhah_reject', 'می\u200cتواند تنخواه را رد کند👎'), ('Tankhah_hq_view', 'رصد دفتر مرکزی'), ('Tankhah_hq_approve', '👍تأیید رده بالا در دفتر مرکزی'), ('Tankhah_HQ_OPS_PENDING', 'در حال بررسی - بهره\u200cبرداری'), ('Tankhah_HQ_OPS_APPROVED', '👍تأییدشده - بهره\u200cبرداری'), ('Tankhah_HQ_FIN_PENDING', 'در حال بررسی - مالی'), ('Tankhah_PAID', 'پرداخت\u200cشده'), ('FactorItem_approve', '👍تایید/رد ردیف فاکتور (تایید ردیف فاکتور*استفاده در مراحل تایید*)'), ('edit_full_tankhah', '👍😊تغییرات کاربری در فاکتور /تایید یا رد ردیف ها '), ('Dashboard_Core_view', 'دسترسی به داشبورد Core پایه'), ('DashboardView_flows_view', 'دسترسی به روند تنخواه گردانی'), ('Dashboard__view', 'دسترسی به داشبورد اصلی 💻'), ('Dashboard_Stats_view', 'دسترسی به آمار کلی داشبورد💲')], 'verbose_name': 'تنخواه', 'verbose_name_plural': 'تنخواه\u200cها'},
        ),
        migrations.AlterUniqueTogether(
            name='stageapprover',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع موجودیت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvallog',
            name='object_id',
            field=models.PositiveIntegerField(default=1, verbose_name='شناسه موجودیت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stageapprover',
            name='entity_type',
            field=models.CharField(choices=[('TANKHAH', 'تنخواه'), ('BUDGET_ALLOCATION', 'تخصیص بودجه')], default='TANKHAH', max_length=50, verbose_name='نوع موجودیت'),
        ),
        migrations.AlterUniqueTogether(
            name='stageapprover',
            unique_together={('stage', 'post', 'entity_type')},
        ),
    ]
