# Generated by Django 5.1.7 on 2025-09-21 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_is_admin_action_to_approval_log'),
        ('tankhah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvallog',
            name='is_admin_action',
            field=models.BooleanField(default=False, verbose_name='اقدام ادمین'),
        ),
        migrations.AlterField(
            model_name='stageapprover',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status', verbose_name='مرحله'),
        ),
        migrations.AlterField(
            model_name='tankhahaction',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='مرحله'),
        ),
    ]
