# Generated by Django 5.1.7 on 2025-07-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankhahaction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='tankhahaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده توسط'),
        ),
    ]
