# Generated by Django 5.1.7 on 2025-03-27 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TanbakhFinalApproval',
            new_name='TankhahFinalApproval',
        ),
        migrations.AlterModelOptions(
            name='tankhah',
            options={'default_permissions': (), 'permissions': [('Tankhah_add', 'ثبت تنخواه'), ('Tankhah_update', 'بروزرسانی تنخواه'), ('Tankhah_view', 'نمایش تنخواه'), ('Tankhah_delete', 'حذف تنخواه'), ('Tankhah_part_approve', '👍تأیید رئیس قسمت'), ('Tankhah_approve', '👍تأیید مدیر مجموعه'), ('Tankhah_hq_view', 'رصد دفتر مرکزی'), ('Tankhah_hq_approve', '👍تأیید رده بالا در دفتر مرکزی'), ('Tankhah_HQ_OPS_PENDING', 'در حال بررسی - بهره\u200cبرداری'), ('Tankhah_HQ_OPS_APPROVED', '👍تأییدشده - بهره\u200cبرداری'), ('Tankhah_HQ_FIN_PENDING', 'در حال بررسی - مالی'), ('Tankhah_PAID', 'پرداخت\u200cشده'), ('Tankhah_REJECTED', 'ردشده'), ('FactorItem_approve', '👍تایید/رد ردیف فاکتور دفتر مرکزی '), ('edit_full_tankhah', '👍😊تغییرات کاربری در فاکتور /تایید یا رد ردیف ها '), ('Dashboard_Core_view', 'دسترسی به داشبورد Core پایه'), ('DashboardView_flows_view', 'دسترسی به روند تنخواه گردانی'), ('Dashboard__view', 'دسترسی به داشبورد اصلی 💻')], 'verbose_name': 'تنخواه', 'verbose_name_plural': 'تنخواه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='tankhahfinalapproval',
            options={'default_permissions': (), 'permissions': [('TankhahFinalApproval_view', 'دسترسی تایید یا رد تنخواه گردان ')]},
        ),
        migrations.AlterField(
            model_name='factoritem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='tankhah',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tankhah_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
    ]
