# Generated by Django 5.0.6 on 2025-12-16 04:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مبلغ تخفیف کل فاکتور (ریال)', max_digits=20, verbose_name='تخفیف کل فاکتور'),
        ),
        migrations.AddField(
            model_name='factor',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مبلغ محاسبه شده ارزش افزوده بر اساس مجموع فاکتور', max_digits=20, verbose_name='مبلغ ارزش افزوده'),
        ),
        migrations.AddField(
            model_name='factor',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='درصد ارزش افزوده که در زمان ثبت فاکتور از تنظیمات سیستم گرفته شده است', max_digits=5, verbose_name='درصد ارزش افزوده'),
        ),
        migrations.AddField(
            model_name='factoritem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مبلغ محاسبه شده ارزش افزوده بر اساس مبلغ ردیف', max_digits=25, verbose_name='مبلغ ارزش افزوده'),
        ),
        migrations.AddField(
            model_name='factoritem',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='درصد ارزش افزوده که در زمان ثبت ردیف از تنظیمات سیستم گرفته شده است', max_digits=5, verbose_name='درصد ارزش افزوده'),
        ),
    ]
