# Generated by Django 5.1.7 on 2025-04-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoritem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='مبلغ'),
        ),
    ]
