# Generated by Django 5.1.7 on 2025-04-29 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0002_alter_factoritem_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CustomUser_related', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
    ]
