# Generated by Django 5.1.7 on 2025-04-21 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_remove_budgetallocation_remaining_amount'),
        ('tankhah', '0002_alter_tankhah_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factor',
            options={'default_permissions': (), 'permissions': [('a_factor_add', 'افزودن فاکتور'), ('a_factor_view', 'نمایش فاکتور'), ('a_factor_update', 'بروزرسانی فاکتور'), ('a_factor_delete', 'حذف فاکتور'), ('a_factor_approve', 'تأیید فاکتور'), ('a_factor_reject', 'رد فاکتور')], 'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتورها'},
        ),
        migrations.AlterModelOptions(
            name='tankhah',
            options={'default_permissions': (), 'permissions': [('tankhah_add', ' + افزودن تنخواه'), ('tankhah_view', 'نمایش تنخواه'), ('tankhah_update', '🆙بروزرسانی تنخواه'), ('tankhah_delete', '⛔حذف تنخواه'), ('tankhah_approve', '👍تأیید تنخواه'), ('tankhah_reject', 'رد تنخواه👎')], 'verbose_name': 'تنخواه', 'verbose_name_plural': 'تنخواه\u200cها'},
        ),
        migrations.AddField(
            model_name='tankhah',
            name='project_budget_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tankhahs', to='budgets.projectbudgetallocation', verbose_name='تخصیص بودجه پروژه'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING', 'در انتظار تأیید'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده'), ('PAID', 'پرداخت شده')], default='PENDING', max_length=20, verbose_name='وضعیت'),
        ),
    ]
