# Generated by Django 5.1.7 on 2025-07-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0002_tankhahaction_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankhactiontype',
            name='code',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tankhactiontype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tankhactiontype',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
