# Generated by Django 5.1.7 on 2025-03-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0002_rename_tanbakhfinalapproval_tankhahfinalapproval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoritem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=25, verbose_name='تعداد'),
        ),
    ]
