# Generated by Django 5.1.7 on 2025-05-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0002_rename_created_at_factoritem_created_at_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factoritem',
            old_name='created_at_a',
            new_name='created_at',
        ),
    ]
