# Generated by Django 5.1.7 on 2025-04-11 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_project_options_alter_subproject_options_and_more'),
        ('tankhah', '0002_tankhah_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankhah',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tankhah_set', to='core.project', verbose_name='پروژه'),
        ),
    ]
