# Generated by Django 5.1.7 on 2025-09-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0002_add_is_admin_action_to_approval_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWorkflowControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('admin_workflow_control', 'دسترسی به کنترل گردش کار ادمین'), ('admin_change_status', 'تغییر وضعیت توسط ادمین'), ('admin_reset_workflow', 'بازنشانی گردش کار توسط ادمین'), ('admin_workflow_dashboard', 'دسترسی به داشبورد گردش کار ادمین')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
