# Generated by Django 5.1.7 on 2025-03-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0003_alter_factoritem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tankhahdocument',
            options={'default_permissions': (), 'permissions': [('TankhahDocument_view', 'نمایش اسناد فاکتور منتهی به تنخواه'), ('TankhahDocument_add', 'افزودن اسناد فاکتور منتهی به تنخواه'), ('TankhahDocument_update', 'بروزرسانی اسناد فاکتور منتهی به تنخواه'), ('TankhahDocument_delete', 'حــذف اسناد فاکتور منتهی به تنخواه')]},
        ),
    ]
