# Generated by Django 5.1.7 on 2025-05-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0003_rename_created_at_a_factoritem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoritem',
            name='transaction_type',
        ),
    ]
