# Generated by Django 5.1.7 on 2025-05-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0003_factor_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='کلید شمارنده')),
                ('last_serial', models.PositiveIntegerField(default=0, verbose_name='آخرین شماره سریال')),
            ],
            options={
                'verbose_name': 'شمارنده سریال فاکتور',
                'verbose_name_plural': 'شمارنده\u200cهای سریال فاکتور',
            },
        ),
    ]
