# Generated by Django 5.1.7 on 2025-07-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0003_tankhactiontype_code_tankhactiontype_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankhactiontype',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='تایپ'),
        ),
        migrations.AlterField(
            model_name='tankhactiontype',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='tankhactiontype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
