# Generated by Django 5.1.7 on 2025-07-12 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0004_alter_tankhactiontype_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='re_registered_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='re_registered_factors', to='tankhah.tankhah', verbose_name='تنخواه جدید'),
        ),
        migrations.AddField(
            model_name='factor',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل رد'),
        ),
    ]
