# Generated by Django 5.1.7 on 2025-04-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_code'),
        ('tankhah', '0004_alter_tankhah_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stageapprover',
            unique_together={('post', 'stage')},
        ),
    ]
