# Generated by Django 5.1.7 on 2025-05-05 05:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tankhah', '0004_remove_factoritem_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factor',
            options={'default_permissions': (), 'permissions': [('factor_add', 'افزودن فاکتور'), ('factor_view', 'نمایش فاکتور'), ('factor_update', 'بروزرسانی فاکتور'), ('factor_delete', 'حذف فاکتور'), ('factor_approve', 'تأیید فاکتور'), ('factor_reject', 'رد فاکتور')], 'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتورها'},
        ),
        migrations.RemoveIndex(
            model_name='factor',
            name='tankhah_fac_number_f3bf46_idx',
        ),
        migrations.AddField(
            model_name='factor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factor',
            name='is_emergency',
            field=models.BooleanField(default=False, verbose_name='اضطراری'),
        ),
        migrations.AddField(
            model_name='factor',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factors', to='core.project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='factor',
            name='subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factors', to='core.subproject', verbose_name='زیرپروژه'),
        ),
        migrations.AddIndex(
            model_name='factor',
            index=models.Index(fields=['number', 'date', 'status', 'tankhah'], name='tankhah_fac_number_940511_idx'),
        ),
    ]
