# Generated by Django 5.1.7 on 2025-04-01 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0004_alter_tankhahdocument_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='tankhah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='tankhah.tankhah', verbose_name='تنخواه'),
        ),
    ]
