# Generated by Django 5.1.7 on 2025-05-05 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0005_alter_factor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('min_stage_order', models.IntegerField(default=1, verbose_name='حداقل ترتیب مرحله')),
            ],
        ),
        migrations.RemoveField(
            model_name='factor',
            name='project',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='subproject',
        ),
        migrations.AlterField(
            model_name='factoritem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tankhah.itemcategory', verbose_name='دسته\u200cبندی'),
        ),
    ]
