# Generated by Django 5.1.7 on 2025-04-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0005_alter_stageapprover_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallog',
            name='action',
            field=models.CharField(choices=[('APPROVE', 'تأیید'), ('REJECT', 'رد'), ('RETURN', 'بازگشت'), ('CANCEL', 'لغو')], max_length=25, verbose_name='اقدام'),
        ),
    ]
