# Generated by Django 5.1.7 on 2025-07-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0005_factor_re_registered_in_factor_rejected_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factor',
            options={'default_permissions': (), 'permissions': [('factor_add', 'افزودن فاکتور'), ('factor_view', 'نمایش فاکتور'), ('factor_update', 'بروزرسانی فاکتور'), ('factor_delete', 'حذف فاکتور'), ('factor_approve', ' 👍تایید/رد ردیف فاکتور (تایید ردیف فاکتور*استفاده در مراحل تایید*)'), ('factor_reject', 'رد فاکتور'), ('Factor_full_edit', 'دسترسی کامل به فاکتور'), ('factor_unlock', 'باز کردن فاکتور قفل\u200cشده')], 'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتورها'},
        ),
    ]
