# Generated by Django 5.1.7 on 2025-04-01 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_timelockmodel'),
        ('tankhah', '0005_alter_factor_tankhah'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='locked_by_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workflowstage', verbose_name='قفل شده توسط مرحله'),
        ),
    ]
