# Generated by Django 5.1.7 on 2025-04-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0006_alter_approvallog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallog',
            name='action',
            field=models.CharField(choices=[('APPROVE', 'تأیید'), ('REJECT', 'رد'), ('STAGE_CHANGE', 'تغییر مرحله'), ('NONE', 'هیچکدام')], max_length=25, verbose_name='اقدام'),
        ),
    ]
