# Generated by Django 5.1.7 on 2025-05-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0006_itemcategory_remove_factor_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'permissions': [('ItemCategory_add', 'افزودن دسته بندی نوع هزینه کرد'), ('ItemCategory_update', 'ویرایش دسته بندی نوع هزینه کرد'), ('ItemCategory_view', 'نمایش دسته بندی نوع هزینه کرد'), ('ItemCategory_delete', 'حــذف دسته بندی نوع هزینه کرد')], 'verbose_name': 'دسته بندی نوع هزینه کرد', 'verbose_name_plural': 'دسته بندی نوع هزینه کرد'},
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='factoritem',
            name='min_stage_order',
            field=models.IntegerField(default=1, editable=False, help_text='این نوع تراکنش فقط در این مرحله یا بالاتر مجاز است', verbose_name='حداقل ترتیب مرحله'),
        ),
    ]
