# Generated by Django 5.1.7 on 2025-05-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0007_alter_itemcategory_options_itemcategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoritem',
            name='min_stage_order',
            field=models.IntegerField(default=1, help_text='این نوع تراکنش فقط در این مرحله یا بالاتر مجاز است', verbose_name='حداقل ترتیب مرحله'),
        ),
    ]
