# Generated by Django 5.1.7 on 2025-04-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0007_alter_tankhah_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankhah',
            name='payment_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پرداخت'),
        ),
    ]
