# Generated by Django 5.1.7 on 2025-04-08 11:12

import tankhah.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0007_alter_approvallog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='مبلغ فاکتور'),
        ),
        migrations.AlterField(
            model_name='factordocument',
            name='file',
            field=models.FileField(upload_to=tankhah.models.tankhah_document_path, verbose_name='فایل پیوست'),
        ),
    ]
