# Generated by Django 5.1.7 on 2025-05-05 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0008_alter_factoritem_min_stage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoritem',
            name='category',
        ),
        migrations.AddField(
            model_name='factor',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tankhah.itemcategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='factoritem',
            name='min_stage_order',
            field=models.IntegerField(default=1, editable=False, help_text='این نوع تراکنش فقط در این مرحله یا بالاتر مجاز است', verbose_name='حداقل ترتیب مرحله'),
        ),
    ]
