# Generated by Django 5.1.7 on 2025-04-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0008_tankhah_payment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankhah',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='قفل شده'),
        ),
    ]
