# Generated by Django 5.1.7 on 2025-04-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0008_alter_factor_amount_alter_factordocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factordocument',
            name='file',
            field=models.FileField(upload_to='factors/documents/%Y/%m/%d/', verbose_name='فایل پیوست'),
        ),
    ]
