# Generated by Django 5.1.7 on 2025-04-08 11:20

import tankhah.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0009_alter_factordocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factordocument',
            name='file',
            field=models.FileField(upload_to=tankhah.models.factor_document_upload_path, verbose_name='فایل پیوست'),
        ),
    ]
