# Generated by Django 5.1.7 on 2025-05-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0010_factordocument_uploaded_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factor',
            options={'default_permissions': (), 'permissions': [('factor_add', 'افزودن فاکتور'), ('factor_view', 'نمایش فاکتور'), ('factor_update', 'بروزرسانی فاکتور'), ('factor_delete', 'حذف فاکتور'), ('factor_approve', 'تأیید فاکتور'), ('factor_reject', 'رد فاکتور'), ('Factor_full_edit', 'رد فاکتور')], 'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتورها'},
        ),
    ]
