# Generated by Django 5.1.7 on 2025-05-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0012_alter_factor_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
