# Generated by Django 5.1.7 on 2025-05-09 04:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tankhah', '0013_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('CREATION', 'ایجاد'), ('UPDATE', 'ویرایش'), ('STATUS_CHANGE', 'تغییر وضعیت'), ('DELETION', 'حذف')], max_length=20, verbose_name='نوع تغییر')),
                ('change_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان تغییر')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای قبلی')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای جدید')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تغییر توسط')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tankhah.factor', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'تاریخچه فاکتور',
                'verbose_name_plural': 'تاریخچه\u200cهای فاکتور',
                'ordering': ['-change_timestamp'],
            },
        ),
    ]
