# Generated by Django 5.1.7 on 2025-04-09 20:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_organization_parent_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('payee_type', models.CharField(choices=[('VENDOR', 'فروشنده'), ('EMPLOYEE', 'کارمند'), ('OTHER', 'دیگر')], max_length=20, verbose_name='نوع')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی/اقتصادی')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب')),
                ('iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='شبا')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
            ],
            options={
                'verbose_name': 'دریافت\u200cکننده',
                'verbose_name_plural': 'دریافت\u200cکنندگان',
                'permissions': [('Payee_add', 'افزودن دریافت\u200cکننده'), ('Payee_view', 'نمایش دریافت\u200cکننده'), ('Payee_update', 'بروزرسانی دریافت\u200cکننده'), ('Payee_delete', 'حذف دریافت\u200cکننده')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='شماره دستور پرداخت')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ صدور')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='مبلغ')),
                ('description', models.TextField(verbose_name='شرح پرداخت')),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه پرداخت')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING_SIGNATURES', 'در انتظار امضا'), ('ISSUED', 'صادر شده'), ('PAID', 'پرداخت شده'), ('CANCELED', 'لغو شده')], default='DRAFT', max_length=20, verbose_name='وضعیت')),
                ('min_signatures', models.IntegerField(default=1, verbose_name='حداقل تعداد امضا')),
            ],
            options={
                'verbose_name': 'دستور پرداخت',
                'verbose_name_plural': 'دستورهای پرداخت',
                'permissions': [('PaymentOrder_add', 'افزودن دستور پرداخت'), ('PaymentOrder_view', 'نمایش دستور پرداخت'), ('PaymentOrder_update', 'بروزرسانی دستور پرداخت'), ('PaymentOrder_delete', 'حذف دستور پرداخت'), ('PaymentOrder_sign', 'امضای دستور پرداخت'), ('PaymentOrder_issue', 'صدور دستور پرداخت')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ (ریال)')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='بودجه تخصیصی (ریال)')),
                ('remaining_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='بودجه باقیمانده')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده'), ('PAID', 'پرداخت شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تنخواه',
                'verbose_name_plural': 'تنخواه\u200cها',
                'permissions': [('PettyCash_view', 'نمایش تنخواه'), ('PettyCash_add', 'افزودن تنخواه'), ('PettyCash_update', 'بروزرسانی تنخواه'), ('PettyCash_delete', 'حذف تنخواه')],
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('requires_extra_approval', models.BooleanField(default=False, verbose_name='نیاز به تأیید اضافی')),
            ],
            options={
                'verbose_name': 'نوع تراکنش',
                'verbose_name_plural': 'انواع تراکنش',
                'permissions': [('TransactionType_add', 'افزودن نوع تراکنش'), ('TransactionType_view', 'نمایش نوع تراکنش'), ('TransactionType_update', 'بروزرسانی نوع تراکنش'), ('TransactionType_delete', 'حذف نوع تراکنش')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دوره بودجه')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='مبلغ کل')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='باقی\u200cمانده کل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_archived', models.BooleanField(default=False, verbose_name='بایگانی شده')),
                ('lock_condition', models.CharField(choices=[('AFTER_DATE', 'بعد از تاریخ پایان'), ('MANUAL', 'دستی')], default='AFTER_DATE', max_length=50, verbose_name='شرط قفل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_periods_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('organization', models.ForeignKey(limit_choices_to={'org_type': 'HQ'}, on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='دفتر مرکزی')),
            ],
            options={
                'verbose_name': 'دوره بودجه',
                'verbose_name_plural': 'دوره\u200cهای بودجه',
                'permissions': [('BudgetPeriod_add', 'افزودن دوره بودجه'), ('BudgetPeriod_update', 'بروزرسانی دوره بودجه'), ('BudgetPeriod_view', 'نمایش دوره بودجه'), ('BudgetPeriod_delete', 'حذف دوره بودجه'), ('BudgetPeriod_archive', 'بایگانی دوره بودجه')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='مبلغ تخصیص')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='باقی\u200cمانده تخصیص')),
                ('allocation_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تخصیص')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_allocations_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='سازمان دریافت\u200cکننده')),
                ('budget_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='budgets.budgetperiod', verbose_name='دوره بودجه')),
            ],
            options={
                'verbose_name': 'تخصیص بودجه',
                'verbose_name_plural': 'تخصیص\u200cهای بودجه',
                'permissions': [('BudgetAllocation_add', 'افزودن تخصیص بودجه'), ('BudgetAllocation_view', 'نمایش تخصیص بودجه'), ('BudgetAllocation_update', 'بروزرسانی تخصیص بودجه'), ('BudgetAllocation_delete', 'حذف تخصیص بودجه'), ('budgetallocation_adjust', 'تنظیم تخصیص بودجه (افزایش/کاهش)')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ALLOCATION', 'تخصیص اولیه'), ('CONSUMPTION', 'مصرف'), ('ADJUSTMENT_INCREASE', 'افزایش تخصیص'), ('ADJUSTMENT_DECREASE', 'کاهش تخصیص')], max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='مبلغ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budgets.budgetallocation', verbose_name='تخصیص بودجه')),
            ],
            options={
                'verbose_name': 'تراکنش بودجه',
                'verbose_name_plural': 'تراکنش\u200cهای بودجه',
                'permissions': [('BudgetTransaction_view', 'نمایش تراکنش بودجه')],
                'default_permissions': (),
            },
        ),
    ]
