# Generated by Django 5.1.7 on 2025-09-25 08:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CREATE', 'ایجاد'), ('UPDATE', 'بروزرسانی'), ('STOP', 'توقف'), ('REALLOCATE', 'انتقال'), ('RETURN', 'برگشت')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='رقم عدد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='اکشن در تاریخ و ساعت')),
                ('details', models.TextField(blank=True, verbose_name='جزئیات')),
                ('transaction_type', models.CharField(choices=[('ALLOCATION', 'تخصیص'), ('CONSUMPTION', 'مصرف'), ('RETURN', 'برگشت')], max_length=20, verbose_name='نوع تراکنش')),
                ('transaction_id', models.CharField(max_length=250, unique=True, verbose_name='شناسه تراکنش')),
            ],
            options={
                'verbose_name': 'تاریخچه بودجه',
                'verbose_name_plural': 'تاریخچه\u200cهای بودجه',
                'permissions': [('BudgetHistory_add', 'افزودن تاریخچه برای هر بودجه کلان'), ('BudgetHistory_view', ' نمایش تاریخچه هر بودجه کلان'), ('BudgetHistory_update', 'بروزرسانی تاریخچه برای هر بودجه کلان'), ('BudgetHistory_delete', ' حــذف تاریخچه برای هر بودجه کلان')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام ردیف بودجه')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد ردیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت ')),
            ],
            options={
                'verbose_name': 'ردیف بودجه',
                'verbose_name_plural': 'ردیف\u200cهای بودجه',
                'permissions': [('BudgetItem_add', 'افزودن ردیف بودجه'), ('BudgetItem_update', 'ویرایش ردیف بودجه'), ('BudgetItem_view', 'نمایش ردیف بودجه'), ('BudgetItem_delete', 'حــذف ردیف بودجه')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دوره بودجه')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=25, verbose_name='مبلغ کل')),
                ('total_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='مجموع تخصیص\u200cها')),
                ('returned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='مجموع بودجه برگشتی')),
                ('locked_percentage', models.IntegerField(default=0, help_text='درصد بودجه که قفل می\u200cشود (0-100)', verbose_name='درصد قفل\u200cشده')),
                ('warning_threshold', models.DecimalField(decimal_places=2, default=10, help_text='درصدی که هشدار نمایش داده می\u200cشود (0-100)', max_digits=5, verbose_name='آستانه اخطار')),
                ('warning_action', models.CharField(choices=[('NOTIFY', 'فقط اعلان'), ('LOCK', 'قفل کردن'), ('RESTRICT', 'محدود کردن ثبت')], default='NOTIFY', help_text='رفتار سیستم هنگام رسیدن به آستانه هشدار', max_length=50, verbose_name='اقدام هشدار')),
                ('allocation_phase', models.CharField(blank=True, max_length=50, verbose_name='فاز تخصیص')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_archived', models.BooleanField(default=False, verbose_name='بایگانی شده')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تمام\u200cشده')),
                ('lock_condition', models.CharField(choices=[('AFTER_DATE', 'بعد از تاریخ پایان'), ('MANUAL', 'دستی'), ('ZERO_REMAINING', 'باقی\u200cمانده صفر')], default='AFTER_DATE', max_length=50, verbose_name='شرط قفل')),
            ],
            options={
                'verbose_name': 'دوره بودجه',
                'verbose_name_plural': 'دوره\u200cهای بودجه',
                'permissions': [('budgetperiod_add', 'افزودن دوره بودجه'), ('budgetperiod_update', 'بروزرسانی دوره بودجه'), ('budgetperiod_view', 'نمایش دوره بودجه'), ('budgetperiod_delete', 'حذف دوره بودجه'), ('budgetperiod_archive', 'بایگانی دوره بودجه')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetReallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25)),
                ('reallocation_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BudgetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('PERIOD', 'دوره بودجه'), ('ALLOCATION', 'تخصیص'), ('PROJECT', 'پروژه')], max_length=50)),
                ('locked_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('warning_threshold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('warning_action', models.CharField(choices=[('NOTIFY', 'اعلان'), ('LOCK', 'قفل'), ('RESTRICT', 'محدود')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ALLOCATION', 'تخصیص اولیه'), ('CONSUMPTION', 'مصرف / هزینه'), ('ADJUSTMENT_INCREASE', 'افزایش تخصیص'), ('ADJUSTMENT_DECREASE', 'کاهش تخصیص'), ('RETURN', 'برگشت به بودجه')], max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='مبلغ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('transaction_id', models.CharField(max_length=250, unique=True, verbose_name='شناسه تراکنش')),
                ('client_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP ثبت\u200cکننده')),
                ('client_host', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام میزبان/کامپیوتر')),
            ],
            options={
                'verbose_name': 'تراکنش بودجه',
                'verbose_name_plural': 'تراکنش\u200cهای بودجه',
                'permissions': [('BudgetTransaction_add', 'افزودن تراکنش بودجه'), ('BudgetTransaction_update', 'بروزرسانی تراکنش بودجه'), ('BudgetTransaction_delete', 'حــذف تراکنش بودجه'), ('BudgetTransaction_view', 'نمایش تراکنش بودجه'), ('BudgetTransaction_return', 'برگشت تراکنش بودجه')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetTransferReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'دسترسی برای جابجایی و برگشت بودجه',
                'verbose_name_plural': 'دسترسی برای جابجایی و برگشت بودجه',
                'permissions': [('BudgetTransfer', 'دسترسی جابجایی بودجه'), ('BudgetReturn', 'دسترسی برگشت جابجایی بودجه')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مرکز هزینه')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد مرکز هزینه')),
                ('allocated_budget', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='بودجه تخصیص\u200cیافته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مرکز هزینه',
                'verbose_name_plural': 'مراکز هزینه',
            },
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('INDIVIDUAL', 'شخص حقیقی'), ('LEGAL', 'شخص حقوقی')], default='INDIVIDUAL', max_length=30, verbose_name='ماهیت شخص')),
                ('name', models.CharField(blank=True, help_text='برای اشخاص حقیقی', max_length=100, null=True, verbose_name='نام')),
                ('family', models.CharField(blank=True, help_text='برای اشخاص حقیقی', max_length=100, null=True, verbose_name='نام خانوادگی')),
                ('legal_name', models.CharField(blank=True, help_text='برای اشخاص حقوقی', max_length=200, null=True, verbose_name='نام حقوقی')),
                ('brand_name', models.CharField(blank=True, help_text='برای اشخاص حقوقی', max_length=200, null=True, verbose_name='نام تجاری')),
                ('national_id', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid_national_id', message='کد ملی باید 10 رقم و شناسه حقوقی 11 رقم باشد.', regex='^\\d{10,11}$')], verbose_name='کد ملی/شناسه حقوقی')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب')),
                ('iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='شبا')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه مالیاتی')),
                ('payee_type', models.CharField(choices=[('VENDOR', 'فروشنده'), ('EMPLOYEE', 'کارمند'), ('OTHER', 'سایر')], max_length=20, verbose_name='نوع دریافت\u200cکننده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دریافت\u200cکننده',
                'verbose_name_plural': 'دریافت\u200cکنندگان',
                'permissions': [('Payee_add', 'افزودن دریافت\u200cکننده'), ('Payee_view', 'نمایش دریافت\u200cکننده'), ('Payee_update', 'بروزرسانی دریافت\u200cکننده'), ('Payee_delete', 'حذف دریافت\u200cکننده')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=None, max_length=50, unique=True, verbose_name='شماره دستور پرداخت')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ صدور')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='مبلغ (ریال)')),
                ('description', models.TextField(blank=True, verbose_name='شرح پرداخت')),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه پرداخت')),
                ('min_signatures', models.IntegerField(default=1, verbose_name='حداقل تعداد امضا')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('payee_account_number', models.IntegerField(blank=True, null=True, verbose_name='شماره حساب')),
                ('payee_iban', models.IntegerField(blank=True, null=True, verbose_name='شبا')),
                ('payment_tracking_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='شناسه پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_locked', models.BooleanField(default=False, verbose_name='قفل شده')),
                ('is_archived', models.BooleanField(default=False, help_text='آیا این دستور پرداخت آرشیو شده است؟', verbose_name='آرشیو شده')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آرشیو')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
            ],
            options={
                'verbose_name': 'دستور پرداخت',
                'verbose_name_plural': 'دستورهای پرداخت',
                'ordering': ['-created_at'],
                'permissions': [('PaymentOrder_add', 'افزودن دستور پرداخت'), ('PaymentOrder_view', 'نمایش دستور پرداخت'), ('PaymentOrder_update', 'بروزرسانی دستور پرداخت'), ('PaymentOrder_delete', 'حذف دستور پرداخت'), ('PaymentOrder_sign', 'امضای دستور پرداخت'), ('PaymentOrder_issue', 'صدور دستور پرداخت')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('requires_extra_approval', models.BooleanField(default=False, verbose_name='نیاز به تأیید اضافی')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='گروه بندی تراکنش\u200cها ')),
                ('transaction_flow', models.CharField(choices=[('INFLOW', 'ورودی (افزایش بودجه)'), ('OUTFLOW', 'خروجی (کاهش بودجه)'), ('CONSUMPTION', 'مصرف بودجه'), ('TRANSFER', 'انتقال بودجه'), ('RETURN', 'بازگشت بودجه'), ('ADJUSTMENT', 'تعدیل بودجه')], help_text='جهت جریان مالی این نوع تراکنش (ورودی، خروجی، مصرف و غیره)', max_length=20, verbose_name='جریان تراکنش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نوع تراکنش',
                'verbose_name_plural': 'انواع تراکنش',
                'permissions': [('TransactionType_add', 'افزودن نوع تراکنش'), ('TransactionType_view', 'نمایش نوع تراکنش'), ('TransactionType_update', 'بروزرسانی نوع تراکنش'), ('TransactionType_delete', 'حذف نوع تراکنش')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='مبلغ تخصیص')),
                ('allocation_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تخصیص')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('allocation_type', models.CharField(choices=[('amount', 'مبلغ ثابت'), ('percent', 'درصد'), ('returned', 'برگشتی')], default='amount', max_length=20, verbose_name='نوع تخصیص')),
                ('locked_percentage', models.DecimalField(decimal_places=2, default=0, help_text='درصد تخصیص که قفل می\u200cشود (0-100)', max_digits=5, verbose_name='درصد قفل\u200cشده')),
                ('warning_threshold', models.DecimalField(decimal_places=2, default=10, help_text='درصدی که هشدار نمایش داده می\u200cشود (0-100)', max_digits=5, verbose_name='آستانه اخطار')),
                ('warning_action', models.CharField(choices=[('NOTIFY', 'فقط اعلان'), ('LOCK', 'قفل کردن'), ('RESTRICT', 'محدود کردن ثبت')], default='NOTIFY', help_text='رفتار سیستم هنگام رسیدن به آستانه هشدار', max_length=50, verbose_name='اقدام هشدار')),
                ('allocation_number', models.IntegerField(default=1, verbose_name='شماره تخصیص')),
                ('returned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='مجموع بودجه برگشتی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_locked', models.BooleanField(default=False, verbose_name='قفل\u200cشده')),
                ('is_stopped', models.BooleanField(default=False, verbose_name='متوقف\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ ایجاد بودجه . خودکار سیستم ', verbose_name='تاریخ ایجاد ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_allocations_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'تخصیص بودجه',
                'verbose_name_plural': 'تخصیص\u200cهای بودجه',
                'db_table': 'budgets_budgetallocation',
                'permissions': [('budgetallocation_add', 'افزودن تخصیص بودجه'), ('budgetallocation_view', 'نمایش تخصیص بودجه'), ('budgetallocation_update', 'بروزرسانی تخصیص بودجه'), ('budgetallocation_delete', 'حذف تخصیص بودجه'), ('budgetallocation_adjust', 'تنظیم تخصیص بودجه (افزایش/کاهش)'), ('budgetallocation_stop', 'توقف تخصیص بودجه'), ('budgetallocation_return', 'برگشت تخصیص بودجه'), ('BudgetAllocation_approve', 'می\u200cتواند تخصیص بودجه را تأیید کند'), ('BudgetAllocation_reject', 'می\u200cتواند تخصیص بودجه را رد کند')],
                'default_permissions': (),
            },
        ),
    ]
