# Generated by Django 4.2.7 on 2025-11-17 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='created_by_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post', verbose_name='پست ایجادکننده'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders_organize', to='core.organization', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='پردازش توسط'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='budgets.payee', verbose_name='دریافت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='core.project', verbose_name='پروژه'),
        ),
    ]
