# Generated by Django 5.1.7 on 2025-04-16 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('contenttypes', '0004_alter_contenttype_id'),
        ('core', '0001_initial'),
        ('tankhah', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='core.organization', verbose_name='سازمان دریافت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='budgethistory',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='budgethistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='core.organization', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='budget_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='budgets.budgetitem', verbose_name='ردیف بودجه'),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_periods_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_periods', to='core.organization', verbose_name='دفتر مرکزی'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='budget_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='budgets.budgetperiod', verbose_name='دوره بودجه'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='budget_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='budgets.budgetperiod', verbose_name='دوره بودجه'),
        ),
        migrations.AddField(
            model_name='budgetreallocation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetreallocation',
            name='source_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reallocations_from', to='budgets.budgetallocation'),
        ),
        migrations.AddField(
            model_name='budgetreallocation',
            name='target_allocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reallocations_to', to='budgets.budgetallocation'),
        ),
        migrations.AddField(
            model_name='budgetsettings',
            name='budget_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.budgetperiod', verbose_name='دوره بودجه'),
        ),
        migrations.AddField(
            model_name='budgetsettings',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AddField(
            model_name='budgettransaction',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budgets.budgetallocation', verbose_name='تخصیص بودجه'),
        ),
        migrations.AddField(
            model_name='budgettransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='budgettransaction',
            name='related_tankhah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tankhah.tankhah', verbose_name='تنخواه مرتبط'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='budget_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budgetallocation', verbose_name='تخصیص بودجه'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='payee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payees_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='created_by_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post', verbose_name='پست ایجادکننده'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='payee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgets.payee', verbose_name='دریافت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='related_factors',
            field=models.ManyToManyField(blank=True, to='tankhah.factor', verbose_name='فاکتورهای مرتبط'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='tankhah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='tankhah.tankhah', verbose_name='تنخواه'),
        ),
        migrations.AddField(
            model_name='projectbudgetallocation',
            name='budget_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_allocations', to='budgets.budgetallocation', verbose_name='تخصیص بودجه شعبه'),
        ),
        migrations.AddField(
            model_name='projectbudgetallocation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_budget_allocations_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='projectbudgetallocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='core.project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='projectbudgetallocation',
            name='subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='core.subproject', verbose_name='زیرپروژه'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_types_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetitem',
            unique_together={('budget_period', 'organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['budget_period', 'allocation_date'], name='budgets_bud_budget__3d5534_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['organization', 'allocated_amount'], name='budgets_bud_organiz_05ceb0_idx'),
        ),
    ]
