# Generated by Django 5.1.7 on 2025-04-14 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
        ('contenttypes', '0004_alter_contenttype_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costcenter',
            options={'verbose_name': 'مرکز هزینه', 'verbose_name_plural': 'مراکز هزینه'},
        ),
        migrations.AddField(
            model_name='budgethistory',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgethistory',
            name='transaction_id',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='شناسه تراکنش'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='allocation_phase',
            field=models.CharField(blank=True, max_length=50, verbose_name='فاز تخصیص'),
        ),
    ]
