# Generated by Django 4.2.7 on 2025-11-17 18:52

import budgets.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('budgets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tankhah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='related_factors',
            field=models.ManyToManyField(blank=True, related_name='payment_orders', to='tankhah.factor', verbose_name='فاکتورهای مرتبط '),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='related_tankhah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders_tankhah', to='tankhah.tankhah', verbose_name='تنخواه مرتبط'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='status',
            field=models.ForeignKey(blank=True, default=budgets.models.get_default_payment_order_status, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='tankhah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='tankhah.tankhah', verbose_name='تنخواه'),
        ),
        migrations.AddField(
            model_name='payee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payees_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='budget_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budgetallocation', verbose_name='تخصیص بودجه'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='budgettransaction',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budgets.budgetallocation', verbose_name='تخصیص بودجه'),
        ),
        migrations.AddField(
            model_name='budgettransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='budgettransaction',
            name='related_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tankhah.factor', verbose_name='فاکتور مرتبط'),
        ),
        migrations.AddField(
            model_name='budgettransaction',
            name='related_tankhah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tankhah.tankhah', verbose_name='تنخواه مرتبط'),
        ),
        migrations.AddField(
            model_name='budgetsettings',
            name='budget_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.budgetperiod', verbose_name='دوره بودجه'),
        ),
        migrations.AddField(
            model_name='budgetsettings',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AddField(
            model_name='budgetreallocation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetreallocation',
            name='source_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reallocations_from', to='budgets.budgetallocation'),
        ),
        migrations.AddField(
            model_name='budgetreallocation',
            name='target_allocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reallocations_to', to='budgets.budgetallocation'),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_periods_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_periods', to='core.organization', verbose_name='دفتر مرکزی'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='budget_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='budgets.budgetperiod', verbose_name='دوره بودجه'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='core.organization', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='budgethistory',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='budgethistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='budget_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='budgets.budgetitem', verbose_name='ردیف بودجه'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='budget_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='budgets.budgetperiod', verbose_name='دوره بودجه'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_allocations_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='core.organization', verbose_name='سازمان دریافت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='core.subproject', verbose_name='زیرپروژه'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', 'organization'], name='budgets_pay_status__7a985f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['is_archived', 'is_locked'], name='budgets_pay_is_arch_415832_idx'),
        ),
        migrations.AddIndex(
            model_name='payee',
            index=models.Index(fields=['national_id', 'entity_type'], name='budgets_pay_nationa_c50a62_idx'),
        ),
        migrations.AddIndex(
            model_name='payee',
            index=models.Index(fields=['name', 'family'], name='budgets_pay_name_5c66cc_idx'),
        ),
        migrations.AddIndex(
            model_name='payee',
            index=models.Index(fields=['legal_name'], name='budgets_pay_legal_n_6955db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payee',
            unique_together={('entity_type', 'national_id')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetitem',
            unique_together={('budget_period', 'organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['budget_period', 'allocation_date'], name='budgets_bud_budget__3d5534_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['organization', 'allocated_amount'], name='budgets_bud_organiz_05ceb0_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['project'], name='budgets_bud_project_f44008_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['subproject'], name='budgets_bud_subproj_69ce91_idx'),
        ),
    ]
