# Generated by Django 5.1.7 on 2025-05-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ALLOCATION', 'تخصیص اولیه'), ('CONSUMPTION', 'مصرف'), ('ADJUSTMENT_INCREASE', 'افزایش تخصیص'), ('ADJUSTMENT_DECREASE', 'کاهش تخصیص'), ('RETURN', 'بازگشت')], max_length=20, verbose_name='نوع تراکنش'),
        ),
    ]
