# Generated by Django 5.1.7 on 2025-04-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت '),
        ),
    ]
