# Generated by Django 5.1.7 on 2025-06-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
    ]
