# Generated by Django 5.1.7 on 2025-04-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetperiod',
            options={'default_permissions': (), 'verbose_name': 'دوره بودجه', 'verbose_name_plural': 'دوره\u200cهای بودجه'},
        ),
    ]
