# Generated by Django 5.1.7 on 2025-04-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='budgettransaction',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='status',
            field=models.BooleanField(default=1, verbose_name='فعال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payee',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='فعال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='گروه بندی تراکنش\u200cها '),
        ),
        migrations.DeleteModel(
            name='PettyCash',
        ),
    ]
