# Generated by Django 5.1.7 on 2025-07-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='budgetallocation',
            table='budgets_budgetallocation',
        ),
    ]
