# Generated by Django 5.1.7 on 2025-09-28 05:40

import budgets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0002_initial'),
        ('core', '0001_initial'),
        ('tankhah', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettransaction',
            name='related_tankhah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tankhah.tankhah', verbose_name='تنخواه مرتبط'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='budget_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budgetallocation', verbose_name='تخصیص بودجه'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='payee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payees_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='آرشیو شده توسط'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='created_by_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post', verbose_name='پست ایجادکننده'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders_organize', to='core.organization', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='پردازش توسط'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='budgets.payee', verbose_name='دریافت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='core.project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='related_factors',
            field=models.ManyToManyField(blank=True, related_name='payment_orders', to='tankhah.factor', verbose_name='فاکتورهای مرتبط '),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='related_tankhah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders_tankhah', to='tankhah.tankhah', verbose_name='تنخواه مرتبط'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='status',
            field=models.ForeignKey(blank=True, default=budgets.models.get_default_payment_order_status, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='tankhah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='tankhah.tankhah', verbose_name='تنخواه'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_types_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetitem',
            unique_together={('budget_period', 'organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['budget_period', 'allocation_date'], name='budgets_bud_budget__3d5534_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['organization', 'allocated_amount'], name='budgets_bud_organiz_05ceb0_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['project'], name='budgets_bud_project_f44008_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['subproject'], name='budgets_bud_subproj_69ce91_idx'),
        ),
        migrations.AddIndex(
            model_name='payee',
            index=models.Index(fields=['national_id', 'entity_type'], name='budgets_pay_nationa_c50a62_idx'),
        ),
        migrations.AddIndex(
            model_name='payee',
            index=models.Index(fields=['name', 'family'], name='budgets_pay_name_5c66cc_idx'),
        ),
        migrations.AddIndex(
            model_name='payee',
            index=models.Index(fields=['legal_name'], name='budgets_pay_legal_n_6955db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payee',
            unique_together={('entity_type', 'national_id')},
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', 'organization'], name='budgets_pay_status__7a985f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['is_archived', 'is_locked'], name='budgets_pay_is_arch_415832_idx'),
        ),
    ]
