# Generated by Django 5.1.7 on 2025-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='قفل\u200cشده'),
        ),
    ]
