# Generated by Django 5.1.7 on 2025-04-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budgetitem_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='allocation_type',
            field=models.CharField(choices=[('amount', 'مبلغ ثابت'), ('percent', 'درصد'), ('returned', 'برگشتی')], default='amount', max_length=20, verbose_name='نوع تخصیص'),
        ),
    ]
