# Generated by Django 5.1.7 on 2025-05-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budgetallocation_is_locked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetallocation',
            options={'default_permissions': [], 'permissions': [('budgetallocation_add', 'افزودن تخصیص بودجه'), ('budgetallocation_view', 'نمایش تخصیص بودجه'), ('budgetallocation_update', 'بروزرسانی تخصیص بودجه'), ('budgetallocation_delete', 'حذف تخصیص بودجه'), ('budgetallocation_adjust', 'تنظیم تخصیص بودجه (افزایش/کاهش)'), ('budgetallocation_stop', 'توقف تخصیص بودجه'), ('budgetallocation_return', 'برگشت تخصیص بودجه'), ('BudgetAllocation_approve', 'می\u200cتواند تخصیص بودجه را تأیید کند'), ('BudgetAllocation_reject', 'می\u200cتواند تخصیص بودجه را رد کند')], 'verbose_name': 'تخصیص بودجه', 'verbose_name_plural': 'تخصیص\u200cهای بودجه'},
        ),
    ]
