# Generated by Django 5.1.7 on 2025-04-14 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_alter_costcenter_options_budgethistory_content_type_and_more'),
        ('core', '0005_alter_organization_org_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetperiod',
            name='locked_percentage',
            field=models.IntegerField(default=0, help_text='درصد بودجه که قفل می\u200cشود (0-100)', verbose_name='درصد قفل\u200cشده'),
        ),
        migrations.AlterField(
            model_name='budgetperiod',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_periods', to='core.organization', verbose_name='دفتر مرکزی'),
        ),
    ]
