# Generated by Django 5.1.7 on 2025-04-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_alter_budgetallocation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetallocation',
            name='remaining_amount',
        ),
    ]
