# Generated by Django 5.1.7 on 2025-10-11 10:55

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='payee',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='شماره حساب باید 5-20 رقم باشد.', regex='^\\d{5,20}$')], verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='payee',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, validators=[django.core.validators.RegexValidator(message='شبا باید IR + 24 رقم باشد.', regex='^IR[0-9]{2}[0-9]{22}$')], verbose_name='شبا'),
        ),
        migrations.AlterField(
            model_name='payee',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='تلفن باید 09xxxxxxxxx باشد.', regex='^09[0-9]{9}$')], verbose_name='تلفن'),
        ),
    ]
