# Generated by Django 5.1.7 on 2025-09-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetallocation',
            options={'default_permissions': (), 'permissions': [('budgetallocation_add', 'افزودن تخصیص بودجه'), ('budgetallocation_view', 'نمایش تخصیص بودجه'), ('budgetallocation_update', 'بروزرسانی تخصیص بودجه'), ('budgetallocation_delete', 'حذف تخصیص بودجه'), ('budgetallocation_adjust', 'تنظیم تخصیص بودجه (افزایش/کاهش)'), ('budgetallocation_stop', 'توقف تخصیص بودجه'), ('budgetallocation_return', 'برگشت تخصیص بودجه'), ('BudgetAllocation_approve', 'می\u200cتواند تخصیص بودجه را تأیید کند'), ('BudgetAllocation_reject', 'می\u200cتواند تخصیص بودجه را رد کند'), ('BudgetAllocation_reports', 'گزارشات تخصیص بودجه')], 'verbose_name': 'تخصیص بودجه', 'verbose_name_plural': 'تخصیص\u200cهای بودجه'},
        ),
        migrations.AlterModelOptions(
            name='budgetperiod',
            options={'default_permissions': (), 'permissions': [('budgetperiod_add', 'افزودن دوره بودجه'), ('budgetperiod_update', 'بروزرسانی دوره بودجه'), ('budgetperiod_view', 'نمایش دوره بودجه'), ('budgetperiod_delete', 'حذف دوره بودجه'), ('budgetperiod_archive', 'بایگانی دوره بودجه'), ('budgetperiod_reports', 'بایگانی دوره بودجه')], 'verbose_name': 'دوره بودجه', 'verbose_name_plural': 'دوره\u200cهای بودجه'},
        ),
    ]
