# Generated by Django 5.1.7 on 2025-04-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_signaturelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='family',
            field=models.CharField(default=1, max_length=100, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
    ]
