# Generated by Django 5.1.7 on 2025-05-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_alter_budgettransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetperiod',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='قفل\u200cشده'),
        ),
    ]
