# Generated by Django 5.1.7 on 2025-04-14 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_budgetperiod_locked_percentage_and_more'),
        ('core', '0005_alter_organization_org_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['budget_period', 'allocation_date'], name='budgets_bud_budget__3d5534_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['organization', 'allocated_amount'], name='budgets_bud_organiz_05ceb0_idx'),
        ),
    ]
