# Generated by Django 5.1.7 on 2025-05-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_budgetallocation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='tankhah_used_statuses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
