# Generated by Django 5.1.7 on 2025-04-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_payee_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetperiod',
            name='locked_percentage',
            field=models.DecimalField(decimal_places=0, default=1, help_text='درصد بودجه که قفل می\u200cشود (۰-۱۰۰)', max_digits=5, verbose_name='درصد قفل\u200cشده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='warning_threshold',
            field=models.DecimalField(decimal_places=0, default=1, help_text='درصدی که اخطار نمایش داده می\u200cشود (۰-۱۰۰)', max_digits=5, verbose_name='آستانه اخطار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='نام'),
        ),
    ]
