# Generated by Django 5.1.7 on 2025-04-17 18:09

import budgets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_remove_budgetitem_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbudgetallocation',
            name='allocation_date',
            field=models.DateField(default=budgets.models.get_current_date, verbose_name='تاریخ تخصیص'),
        ),
    ]
