# Generated by Django 5.0.6 on 2025-10-27 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_payee_created_at_payee_updated_at_and_more'),
        ('tankhah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettransaction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='budgettransaction',
            name='related_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tankhah.factor', verbose_name='فاکتور مرتبط'),
        ),
        migrations.AlterField(
            model_name='budgettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ALLOCATION', 'تخصیص اولیه'), ('CONSUMPTION', 'مصرف / هزینه'), ('COMMITMENT', 'تعهد / رزرو بودجه'), ('ADJUSTMENT_INCREASE', 'افزایش تخصیص'), ('ADJUSTMENT_DECREASE', 'کاهش تخصیص'), ('RETURN', 'برگشت به بودجه')], max_length=20, verbose_name='نوع تراکنش'),
        ),
    ]
