# Generated by Django 5.1.7 on 2025-04-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_alter_projectbudgetallocation_allocation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbudgetallocation',
            name='allocation_date',
            field=models.DateField(verbose_name='تاریخ تخصیص'),
        ),
    ]
