# Generated by Django 5.1.7 on 2025-04-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_budgetallocation_budgets_bud_budget__3d5534_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetperiod',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
