# Generated by Django 5.1.7 on 2025-04-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_alter_budgetperiod_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetperiod',
            options={'default_permissions': (), 'permissions': [('budgetperiod_add', 'افزودن دوره بودجه'), ('budgetperiod_update', 'بروزرسانی دوره بودجه'), ('budgetperiod_view', 'نمایش دوره بودجه'), ('budgetperiod_delete', 'حذف دوره بودجه'), ('budgetperiod_archive', 'بایگانی دوره بودجه')], 'verbose_name': 'دوره بودجه', 'verbose_name_plural': 'دوره\u200cهای بودجه'},
        ),
    ]
