# Generated by Django 5.1.7 on 2025-04-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_budgetperiod_locked_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetperiod',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=25, verbose_name='باقی\u200cمانده کل'),
        ),
        migrations.AlterField(
            model_name='budgetperiod',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, max_digits=25, verbose_name='مبلغ کل'),
        ),
    ]
