# Generated by Django 5.1.7 on 2025-04-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_alter_budgetperiod_remaining_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetperiod',
            name='remaining_amount',
        ),
    ]
