# Generated by Django 5.1.7 on 2025-04-18 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_alter_projectbudgetallocation_allocation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbudgetallocation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='projectbudgetallocation',
            name='allocation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تخصیص'),
        ),
    ]
