# Generated by Django 5.1.7 on 2025-04-14 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_budgetperiod_description'),
        ('core', '0006_organization_is_core'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetallocation',
            options={'default_permissions': (), 'permissions': [('budgetallocation_add', 'افزودن تخصیص بودجه'), ('budgetallocation_view', 'نمایش تخصیص بودجه'), ('budgetallocation_update', 'بروزرسانی تخصیص بودجه'), ('budgetallocation_delete', 'حذف تخصیص بودجه'), ('budgetallocation_adjust', 'تنظیم تخصیص بودجه (افزایش/کاهش)'), ('budgetallocation_stop', 'توقف تخصیص بودجه'), ('budgetallocation_return', 'برگشت تخصیص بودجه')], 'verbose_name': 'تخصیص بودجه', 'verbose_name_plural': 'تخصیص\u200cهای بودجه'},
        ),
        migrations.AlterModelOptions(
            name='budgethistory',
            options={'default_permissions': (), 'permissions': [('BudgetHistory_add', 'افزودن تاریخچه برای هر بودجه کلان'), ('BudgetHistory_view', ' نمایش تاریخچه هر بودجه کلان'), ('BudgetHistory_update', 'بروزرسانی تاریخچه برای هر بودجه کلان'), ('BudgetHistory_delete', ' حــذف تاریخچه برای هر بودجه کلان')], 'verbose_name': 'تاریخچه بودجه', 'verbose_name_plural': 'تاریخچه\u200cهای بودجه'},
        ),
        migrations.AlterModelOptions(
            name='budgettransaction',
            options={'default_permissions': (), 'permissions': [('BudgetTransaction_add', 'افزودن تراکنش بودجه'), ('BudgetTransaction_update', 'بروزرسانی تراکنش بودجه'), ('BudgetTransaction_delete', 'حــذف تراکنش بودجه'), ('BudgetTransaction_view', 'نمایش تراکنش بودجه'), ('BudgetTransaction_return', 'برگشت تراکنش بودجه')], 'verbose_name': 'تراکنش بودجه', 'verbose_name_plural': 'تراکنش\u200cهای بودجه'},
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='باقی\u200cمانده تخصیص'),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.project', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='budgethistory',
            name='action',
            field=models.CharField(choices=[('CREATE', 'ایجاد'), ('UPDATE', 'بروزرسانی'), ('STOP', 'توقف'), ('REALLOCATE', 'انتقال'), ('RETURN', 'برگشت')], max_length=50),
        ),
        migrations.AlterField(
            model_name='budgethistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='رقم عدد'),
        ),
        migrations.AlterField(
            model_name='budgethistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='اکشن در تاریخ و ساعت'),
        ),
        migrations.AlterField(
            model_name='budgethistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده'),
        ),
        migrations.AlterField(
            model_name='budgethistory',
            name='details',
            field=models.TextField(blank=True, verbose_name='جزئیات'),
        ),
        migrations.AlterField(
            model_name='budgethistory',
            name='transaction_type',
            field=models.CharField(choices=[('ALLOCATION', 'تخصیص'), ('CONSUMPTION', 'مصرف'), ('RETURN', 'برگشت')], max_length=20, verbose_name='نوع تراکنش'),
        ),
    ]
