# Generated by Django 5.1.7 on 2025-04-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_remove_budgetperiod_remaining_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
