# Generated by Django 5.1.7 on 2025-04-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_alter_budgetallocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='returned_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='مجموع بودجه برگشتی'),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='returned_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='مجموع بودجه برگشتی'),
        ),
    ]
