# Generated by Django 5.1.7 on 2025-04-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_budgetallocation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetperiod',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام دوره بودجه'),
        ),
    ]
