# Generated by Django 5.1.7 on 2025-04-11 11:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_alter_budgetperiod_name'),
        ('core', '0012_alter_project_options_alter_subproject_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='مبلغ تخصیص')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='باقی\u200cمانده تخصیص')),
                ('allocation_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تخصیص')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('budget_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_allocations', to='budgets.budgetallocation', verbose_name='تخصیص بودجه شعبه')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_budget_allocations_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='core.project', verbose_name='پروژه')),
                ('subproject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='core.subproject', verbose_name='زیرپروژه')),
            ],
            options={
                'verbose_name': 'تخصیص بودجه پروژه',
                'verbose_name_plural': 'تخصیص\u200cهای بودجه پروژه',
                'permissions': [('ProjectBudgetAllocation_add', 'افزودن تخصیص بودجه پروژه'), ('ProjectBudgetAllocation_view', 'نمایش تخصیص بودجه پروژه'), ('ProjectBudgetAllocation_update', 'بروزرسانی تخصیص بودجه پروژه'), ('ProjectBudgetAllocation_delete', 'حذف تخصیص بودجه پروژه'), ('ProjectBudgetAllocation_Head_Office', 'تخصیص بودجه مجموعه پروژه(دفتر مرکزی)🏠'), ('ProjectBudgetAllocation_Branch', 'تخصیص بودجه مجموعه پروژه(شعبه)🏠')],
                'default_permissions': (),
            },
        ),
    ]
