# Generated by Django 5.1.7 on 2025-04-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0010_projectbudgetallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='allocation_type',
            field=models.CharField(choices=[('amount', 'مبلغ'), ('percent', 'درصد')], default='amount', max_length=20, verbose_name='نوع تخصیص'),
        ),
    ]
