# Generated by Django 5.1.7 on 2025-04-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0011_budgetallocation_allocation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocation',
            name='allocation_type',
            field=models.CharField(choices=[('amount', 'مبلغ ثابت'), ('percent', 'درصد')], default='amount', max_length=20, verbose_name='نوع تخصیص'),
        ),
    ]
