# Generated by Django 5.1.7 on 2025-04-12 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0012_alter_budgetallocation_allocation_type'),
        ('core', '0013_alter_project_options_alter_subproject_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetallocation',
            name='remaining_amount',
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.project', verbose_name='پروژه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='status',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
