# Generated by Django 5.1.7 on 2025-04-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0013_remove_budgetallocation_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='فعال'),
            preserve_default=False,
        ),
    ]
